Added three interlinked Spanish terms
carpentries/glosario pull request #103
Opened 2020-10-06 11:38 UTC by callumrollo

## Author: 

- callumrollo

## Language: 

- español

## Terms defined:

- importar
- librería
- módulo

## Editor

@ian-flores

Hi maintainers. I would like to contribute to this project. I see many terms that are defined only in English. Spanish is not my first language, but I have made the best I attempt I can with my knowledge and available tools. if it is inappropriate for a non-native speaker to contribute, please delete this PR.

Best wishes
Callum

2020-10-06 12:46 UTC, callumrollo commented
Updated after reading page https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md linked from Issue #35. This document advises that biblioteca should be used throughout The Carpentries, as librería is an anglicism

2020-12-11 11:26 UTC, ian-flores requested changes

2020-12-11 11:26 UTC, ian-flores commented on glossary.yml
> +    term: "biblioteca"
Hola, creo que deberia ser libreria en vez de biblioteca

2020-12-11 11:26 UTC, ian-flores commented on glossary.yml
> +      un paquete de software reutilizable, también se llama una [biblioteca](#library).
El mismo comentario de arriba, creo que deberia ser libreria.

2020-12-11 11:42 UTC, callumrollo commented on glossary.yml
> +    term: "biblioteca"
Hola, nela primera commit, use libreria. Luego vi en [este documento Carpentries](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md)  de convenciones de traduccion, que se prefiere biblioteca como "el uso de librería ha sido descartado por ser un anglicismo". No obstante, no soy experto. Lo cambiare

2020-12-11 11:50 UTC, callumrollo commented on glossary.yml
> +    term: "biblioteca"
Hecho en 4e6c799

2020-12-11 11:50 UTC, callumrollo commented on glossary.yml
> +      un paquete de software reutilizable, también se llama una [biblioteca](#library).
Hecho en 4e6c799

2020-12-11 12:14 UTC, callumrollo commented
Estes errores de Lint viene del Master 3142544c0d33b713987c5611dde510ebfb00b26d

2020-12-11 13:44 UTC, baileythegreen requested changes
This is failing the linter check because two terms, `absolute error` and `agile development`, have two entries for the Spanish definition.

Absolute error: lines 97 and 125
Agile development: lines 380 and 398

Please remove the duplicate entries, taking into consideration which of the given definitions is more complete.

2020-12-11 13:51 UTC, callumrollo commented
@baileythegreen these duplicate terms have come from Master commit [3142544](https://github.com/carpentries/glosario/commit/3142544c0d33b713987c5611dde510ebfb00b26d). I had to pull fro master to resolve conflicts to complete this PR. I'm not sure what the cleanest way to resolve this is. Maybe Master should be fixed first them I'll pull again?

2020-12-11 14:18 UTC, baileythegreen commented
@callumrollo I see. I'm on it. I'll submit a PR to revert the merge that caused it and ask the Spanish editor to look again.

2020-12-11 17:37 UTC, baileythegreen commented
@callumrollo The PR with the duplicate keys has now been reverted. If you pull from master again, they should be removed from your PR, as well. Then it ought to pass the linter check.

2020-12-11 19:17 UTC, dpshelio commented on glossary.yml
> +    term: "biblioteca"
Hemos usado bibliotecas como traducción de "libraries" en todas nuestras lecciones siguiendo [las convenciones que creamos para ello](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md). También [la documentación traducida de Python](https://docs.python.org/es/3/library/) usa bibliotecas y en [esta introducción a R](https://cran.r-project.org/doc/contrib/R-intro-1.1.0-espanol.1.pdf). Librerías tiene un significado distinto en español, y aunque usado en muchos lugares con dicho significado optamos por mantenerlo con la traducción clásica.
Vease la entrada en la [wikipedia a esta ambigüedad](https://es.wikipedia.org/wiki/Biblioteca_(inform%C3%A1tica)).

2020-12-11 19:19 UTC, dpshelio requested changes

2020-12-11 19:19 UTC, dpshelio commented on glossary.yml
> +    term: "librería"
Vease el comentario "obsoleto" en el hilo https://github.com/carpentries/glosario/pull/103#discussion_r541185464

2020-12-14 15:56 UTC, baileythegreen approved these changes

2020-12-14 15:57 UTC, callumrollo commented
@baileythegreen this should now merge cleanly into master. I've never done such a convoluted PR though so please tell me if I've screwed it up!

@dpshelio gracias por la aclaración

2020-12-14 15:58 UTC, baileythegreen commented
I'm just 'approving' the 'changes' that mean this now passes the linter, because I don't want GitHub to list my review as 'pending' when it isn't needed.

2020-12-18 11:37 UTC, callumrollo commented
Thanks @baileythegreen. Is there any more action needed on my part? Master is advancing and I'd like to get this merged so I can move on other Issues. I think @ian-flores needs to approve the change to biblioteca >> libreria following @dpshelio?

2020-12-18 12:23 UTC, baileythegreen commented
@callumrollo 

Nothing from me, unless you run into lint issues due to upstream additions. Just waiting on Ian.

2021-01-26 17:33 UTC, nicoguaro commented
> @callumrollo
> 
> Nothing from me, unless you run into lint issues due to upstream additions. Just waiting on Ian.

I have been added as an editor. Let me know if  there is something that I can help with.

2021-01-26 22:02 UTC, ian-flores approved these changes

2021-01-26 22:02 UTC, ian-flores commented
Just accepted and will merge now

2021-01-26 22:03 UTC, merged