Adding the terms 'Numpy' and 'SciPy' in en, pt and es, and translate Python from Portuguese and Spanish
carpentries/glosario pull request #127
Opened 2020-10-11 19:20 UTC by leticiadasilva

…se, and adding the translate of the definition of 'Python' in portuguese and spanish.

## Author: 
@leticiadasilva

## Language:  

Portuguese

## Terms defined:
- numpy
- scipy
- python

## Editor

Assign the PR based on the language to the following person:

@beatrizmilz 
@zkamvar
@ian-flores

2020-10-11 19:41 UTC, leticiadasilva commented
If you can adding the label "hacktoberfest-accepted" after the PR will be accepted, I thank you!

2020-10-15 17:04 UTC, zkamvar requested changes
Looks good with minor syntax and spelling changes for English. 

IMO, I don't think we should start the definitions with "Is/Es/É" for the sake of clarity

2020-10-15 19:45 UTC, leticiadasilva commented
@zkamvar thank you for the suggestions! :smiley:

2020-10-20 14:38 UTC, zkamvar approved these changes

2020-10-20 14:39 UTC, zkamvar commented
@ian-flores and @beatrizmilz, do these changes look good?

2020-10-21 01:29 UTC, beatrizmilz reviewed
Oi @leticiadasilva ! Obrigada por suas contribuições e desculpa a demora para revisar. Fiz algumas sugestões buscando deixar padronizado (por exemplo _Open Source_ sugeri mudar para _Código Aberto_), e outras pois parecia que ajudava na fluência da leitura da frase. O que acha das sugestões?

2020-10-21 01:29 UTC, beatrizmilz commented on glossary.yml
> +      É um pacote Python open source que permite trabalhar com arrays, vetores e matrizes de dimensão N,
```suggestion
      É um pacote Python de código aberto que permite trabalhar com arrays, vetores e matrizes de dimensão N, 
```

2020-10-21 01:29 UTC, beatrizmilz commented on glossary.yml
> +      e expressivas para tornar o trabalho com séries temporais estruturadas fácil e
```suggestion
      É um pacote Python de código aberto que oferece estruturas de dados rápidas, flexíveis
      e expressivas para tornar o trabalho com dados estruturados e séries temporais fácil e 
```

2020-10-21 01:29 UTC, beatrizmilz commented on glossary.yml
> +      depende de indentação para definir a estrutura de controle.
```suggestion
      Uma popular linguagem de programação interpretada, de código aberto,  que 
      depende de indentação para definir a estrutura de controle.
```

2020-10-21 15:15 UTC, zkamvar commented on glossary.yml
> +      An open source Python package  that allow work with arrays, vectors and matrices of dimension N,
@beatrizmilz, revised. Thank you for catching that!

2020-10-21 15:39 UTC, zkamvar commented
I'll go ahead and label this with hacktoberfest-accepted so that you can receive credit for it even though the review on this is taking a bit longer than expected.

2020-10-21 16:38 UTC, leticiadasilva commented
@beatrizmilz muito obrigada pelas sugestões, eu adorei! :heart:

2020-10-21 16:38 UTC, leticiadasilva commented
@zkamvar Thank you!!! :smile:

2020-10-21 19:10 UTC, beatrizmilz commented
For me is all great with the translation to Portuguese! @ian-flores Can you check the translations to Spanish, please? Thank you all

2020-12-11 11:27 UTC, ian-flores approved these changes

2020-12-11 11:29 UTC, merged

2025-03-25 12:43 UTC, elletjies commented
@all-contributors please add @leticiadasilva for translation