translate git to Japanese
carpentries/glosario pull request #147
Opened 2020-10-21 08:44 UTC by TomKellyGenetics

## Author: 

- Tom Kelly

## Language: 

- Japanese (ja)

## Terms defined:

- git (note this is romanised in Japanese) see [git wikipedia page](https://ja.wikipedia.org/wiki/Git)

## To do

I think these can be done together:

- git branch
- git clone
- git conflict
- git fork
- git merge
- git pull
- git push
- git remote
-github

If you would rather these were submitted as separate PRs that's ok.

2020-10-27 08:42 UTC, fmichonneau commented on glossary.yml
> +    term "Git(ギット)"
```suggestion
    term: "Git(ギット)"
```

2020-10-27 08:44 UTC, fmichonneau requested changes
there is a `:` missing.
@TomKellyGenetics is this ready to merge otherwise?

2020-10-30 08:14 UTC, TomKellyGenetics commented
Thanks. Yes I think it's ready to merge. Sorry I haven't had time to update with other terms, they're more difficult. I'll send a new PR if I manage it 😃

2020-11-02 09:46 UTC, fmichonneau approved these changes

2020-11-02 09:46 UTC, merged