Translate argument, ascii, assertion to afr. Add fields to empty slug…
carpentries/glosario pull request #198
Opened 2020-11-04 09:03 UTC by jsteyn

…s. Limit lines to 80 characters

## Author: 

- jsteyn

## Language: 

- Arikaans

## Terms defined:

- argument
- ascii
- assertion

## Editor

Assign the PR based on the language to the following person:

| Language   | Person              |
|:----------:|:-------------------:|
| Afrikaans  | @jsteyn, @elletjies |
| French     | @fmichonneau        |

2020-11-04 09:06 UTC, jsteyn commented
My editor does not like empty slugs, so I had to add the basic fields to those, eg:
- slug: someword
  en: ""
  def: >

The editor also reformats all lines to not exceed 80 characters.

I hope these changes are okay.

2020-11-09 16:50 UTC, fmichonneau requested changes
We need to come up with a technical solution to ensure consistent formatting of the pull requests to avoid issues with different text editor configurations. In the case of your pull request, it seems that the re-wrapping of the entries is breaking the links for the Arabic entries. Could you please update your pull request to only include the entries you have added? Thanks!

2020-11-09 16:50 UTC, fmichonneau commented on glossary.yml
> +      يُعبِر عن حقيقة أن ٦٨٪ من القيم تقع ضمن وحدة واحدة من [الانحراف
I think your text editor is changing the order of the words and breaking the links here.

2020-11-09 16:50 UTC, fmichonneau commented on glossary.yml
> +      هي البرامج التى لايتوفر لها دعم من أي برمجيات أُخرى ولم تعد على قيد الصيانة.
same here the order of the words is being changed.

2020-11-09 16:50 UTC, fmichonneau commented on glossary.yml
> +      feedback contínuo ao invés de planejamento de longo prazo. [Programação
it would also be best if the link elements were not broken up

2020-11-09 17:01 UTC, zkamvar commented
I agree with @fmichonneau's comments, but given that this PR is > 1K lines of change, I would suggest instead to close this, and open a new fresh branch.

2020-11-09 17:12 UTC, jsteyn commented
I'll close this issue and create a new branch making the changes as suggested.

2020-11-09 17:12 UTC, closed without merging