Add Jupyter definitions
carpentries/glosario pull request #240
Opened 2020-12-05 01:13 UTC by MysteryBlokHed

## Author: 

- [Adam Thompson-Sharpe](https://github.com/MysteryBlokHed)

## Language: 

- English

## Terms defined:

- Jupyter
- Jupyter Notebook

## Editor

Assign the PR based on the language to the following person:

| Language   | Person                       |
|:----------:|:----------------------------:|
| English    | @baileythegreen, @zkamvar    |

2020-12-05 01:30 UTC, baileythegreen requested changes
These look good. A few small changes. Also, we don't have a definition for IPython, if you would like to add that.

If you haven't already noted this: Jupyter is on the list of terms given in the list in #239. (If that is what prompted this PR, yay! It's working.) When this PR is accepted, it should be noted there.

2020-12-05 01:30 UTC, baileythegreen commented on glossary.yml
> +      in many different programming languages.
```suggestion
      Project Jupyter is a non-profit, open-source project that was born out of the IPython Project
      in 2014 as IPython evolved to support interactive [data science](#data_science) and scientific
      computing in many different programming languages.
```

2020-12-05 01:30 UTC, baileythegreen commented on glossary.yml
> +      The Jupyter Notebook is an open-source web-based [computational notebook](#computational_notebook)
```suggestion
      The Jupyter Notebook is an open-source, web-based [computational notebook](#computational_notebook)
```

2020-12-05 01:30 UTC, baileythegreen commented on glossary.yml
> +      that allows you to write and share live code, equations, visualizations, and narrative text.
```suggestion
      that allows the user to write and share live code, equations, visualisations, and narrative text.
```
For future reference: British spelling is preferred in The Carpentries.

2020-12-05 05:44 UTC, MysteryBlokHed commented
Thank you for the feedback! I've updated the pull request with the suggested changes.

2020-12-05 09:06 UTC, baileythegreen approved these changes

2020-12-07 10:26 UTC, merged

2025-03-25 12:54 UTC, elletjies commented
@all-contributors please add @MysteryBlokHed for translation