Jsteyn
carpentries/glosario pull request #246
Opened 2020-12-09 23:50 UTC by jsteyn

## Author: 

- jsteyn

## Language: 

- English

## Terms defined:

- algorithm
- 
- 

## Editor

Assign the PR based on the language to the following person:

| Language   | Person                       |
|:----------:|:----------------------------:|                  |
| English    | @baileythegreen, @zkamvar    |

2020-12-10 00:23 UTC, baileythegreen requested changes
Looks pretty good. Minor changes requested.

Also note, this is in the list of terms in #239.

2020-12-10 00:23 UTC, baileythegreen commented on glossary.yml
> +      task. In computer science an algorith is a set of instructions for a computer program to solve a
```suggestion
      task. In computer science, an algorithm is a set of instructions in a computer program that solves a 
```

2020-12-10 10:49 UTC, jsteyn commented on glossary.yml
> +      task. In computer science an algorith is a set of instructions for a computer program to solve a
Thanks for that :+1:

2020-12-11 22:54 UTC, baileythegreen approved these changes

2020-12-11 22:54 UTC, merged