Added definition of "byte"
carpentries/glosario pull request #249
Opened 2020-12-11 21:33 UTC by edfoster10

## Author: 

Erin Foster

## Language: 

English

## Terms defined: 

Byte

## Editor

Assign the PR based on the language to the following person:

| Language   | Person                       |
|:----------:|:----------------------------:|
| Afrikaans  | @jsteyn, @elletjies          |
| Arabic     | @BatoolMM                    |
| English    | @baileythegreen, @zkamvar    |
| French     | @fmichonneau                 |
| Japanese   | @tomkellygenetics, @masamiy  |
| Portuguese | @beatrizmilz                 |
| Spanish    | @ian-flores                  |

2020-12-11 22:01 UTC, baileythegreen requested changes

2020-12-11 22:01 UTC, baileythegreen commented on glossary.yml
> +      A unit of digital information that typically consists of eight binary digits, or bits.
```suggestion
      A unit of digital information that typically consists of eight [binary](#binary) digits, or [bits](#bit).
```
I've suggested some internal links to other entries. The definition looks good to me.

2021-01-08 19:09 UTC, baileythegreen approved these changes

2021-01-08 19:09 UTC, merged

2025-07-17 14:27 UTC, elletjies commented
@all-contributors please add @edfoster10 for translation