Update glossary.yml
carpentries/glosario pull request #250
Opened 2020-12-11 22:13 UTC by jananiharan

Added definition for command.

## Author: 

Janani Hariharan

## Language: 

English

## Terms defined:

command

## Editor

Assign the PR based on the language to the following person:

| Language   | Person                       |
|:----------:|:----------------------------:|
| Afrikaans  | @jsteyn, @elletjies          |
| Arabic     | @BatoolMM                    |
| English    | @baileythegreen, @zkamvar    |
| French     | @fmichonneau                 |
| Japanese   | @tomkellygenetics, @masamiy  |
| Portuguese | @beatrizmilz                 |
| Spanish    | @ian-flores                  |

2020-12-11 22:20 UTC, baileythegreen requested changes
Minor change.

2020-12-11 22:20 UTC, baileythegreen commented on glossary.yml
> +      An instruction to a computer program to perform a specific task.
```suggestion
      An instruction telling a computer program to perform a specific task.
```

2020-12-11 22:28 UTC, jananiharan commented on glossary.yml
> +      An instruction to a computer program to perform a specific task.
Looks good to me!

2020-12-11 22:30 UTC, baileythegreen approved these changes

2020-12-11 22:31 UTC, merged

2025-03-25 12:56 UTC, elletjies commented
@all-contributors please add @jananiharan for translation