Translate 5 terminos a español
carpentries/glosario pull request #263
Opened 2020-12-29 19:41 UTC by demar01

## Author: 

-  Maria Dermit

## Language: 

- Spanish

## Terms defined:

- Interfaz de Programación de Aplicaciones
- Teorema de Bayes
- Red Bayesiana
- Stack Overflow
- YAML

## Editor

Assign the PR based on the language to the following person:

| Language   | Person                       |
|:----------:|:----------------------------:|
| Afrikaans  | @jsteyn, @elletjies          |
| Arabic     | @BatoolMM                    |
| English    | @baileythegreen, @zkamvar    |
| French     | @fmichonneau                 |
| Japanese   | @masamiy, @naoe-tatara       |
| Portuguese | @beatrizmilz                 |
| Spanish    | @ian-flores                  |

Please remove the lines not relevant to the language submitted.

2021-01-04 19:52 UTC, fmichonneau commented on glossary.yml
> +      es una manera de representar datos anidados usando identación en lugar de paréntesis   
```suggestion
      es una manera de representar datos anidados usando identación en lugar de paréntesis   
```

2021-01-08 18:40 UTC, ian-flores commented on glossary.yml
> +      Un conjunto de funciones y procedimientos proporcionados por una libreria de softtware o servicio web
Aca creo que deberia ser software

2021-01-08 18:41 UTC, ian-flores commented on glossary.yml
> +      Una gráfica que representa la relacion entre las variables aleatorias para un determinado problema.
En vez de una grafica, pondria "un grafo"

2021-01-08 18:42 UTC, ian-flores commented on glossary.yml
> +      archivos de configuración y en para definir [parámetros](#parameter) en varios estilos
"YAML es usado **frecuentemente** en archivos de configuración **y** para definir [parámetros](#parameter) en varios estilos..."

2021-01-08 18:43 UTC, ian-flores requested changes
Me parecen bien las definiciones pero necesitan unos pequenos ajustes en torno a gramatica. / The definitions look good to me but they need some small adjustments around grammar before merging.

2021-01-14 08:59 UTC, demar01 reviewed
Estoy de acuerdo con los cambios

2021-01-26 22:04 UTC, ian-flores approved these changes

2021-01-26 22:04 UTC, merged

2025-03-25 12:59 UTC, elletjies commented
@all-contributors please add @demar01 for translation