Added definition in english and french for the term: causation
carpentries/glosario pull request #271
Opened 2021-01-27 16:00 UTC by ajneil-gh

## Author: 

- Alastair Neil

## Language: 

- English
- French

## Terms defined:

- causation
-
- 

## Editor

Assign the PR based on the language to the following person:

| Language   | Person                       |
|:----------:|:----------------------------:|
| Afrikaans  | @jsteyn, @elletjies          |
| Arabic     | @BatoolMM                    |
| English    | @baileythegreen, @zkamvar    |
| French     | @fmichonneau                 |
| Japanese   | @masamiy, @naoe-tatara       |
| Portuguese | @beatrizmilz                 |
| Spanish    | @ian-flores                  |

Please remove the lines not relevant to the language submitted.

2021-01-29 18:30 UTC, baileythegreen requested changes
Both the English and French look good to me (as soon as the missing punctuation is added in), but I'm not a French editor, so I'll let one of them take a look.

2021-01-29 18:30 UTC, baileythegreen commented on glossary.yml
> +      produire ou d'affecter un changement dans l'autre
```suggestion
      produire ou d'affecter un changement dans l'autre.
```

2021-02-04 11:10 UTC, fmichonneau approved these changes

2021-02-04 11:11 UTC, fmichonneau approved these changes

2021-02-04 11:14 UTC, baileythegreen approved these changes

2021-02-04 20:52 UTC, merged

2025-07-17 14:25 UTC, elletjies commented
@all-contributors please add @ajneil-gh for translation