added pip and pypi (English)
carpentries/glosario pull request #290
Opened 2021-03-01 18:42 UTC by callumrollo

## Author: 

- Callum Rollo

## Language: 

- English

## Terms defined:

- PyPI
- pip

2021-03-04 15:01 UTC, baileythegreen commented on glossary.yml
> +      of Python packages not included in the standard library.
```suggestion
      The standard [package manager](#package_manager) for [Python](#python). pip enables
      the download and installation of Python packages not included in the standard library.
```


We try to keep lines from getting too wide—no set character limit, but use some longer entries in the file to see where to put line breaks; but don't split words.

2021-03-04 15:02 UTC, baileythegreen commented on glossary.yml
> +      of Python packages not included in the standard library.
Also, `enables` didn't need to be capitalised.

2021-03-04 15:04 UTC, baileythegreen commented on glossary.yml
> +      to PyPI. PyPI packages may install via executed scripts or pre-compiled system-specific wheels.
```suggestion
      The official third-party software repository for [Python](#python). Anyone can upload
      a [package](#package) to PyPI. PyPI packages may install via executed scripts or
      pre-compiled, system-specific wheels.
```

Line breaks again.

2021-03-04 15:05 UTC, baileythegreen commented on glossary.yml
> +    - python
```suggestion
    - python
    - pip
```

2021-03-04 15:05 UTC, baileythegreen commented on glossary.yml
> +    - python
```suggestion
    - pypi
    - python
```

2021-03-04 15:07 UTC, baileythegreen requested changes
I've suggested some additional crosslinks between the two entries (I *think* these should compile okay, since both are being added simultaneously), and changes to line breaks.

2021-03-04 15:41 UTC, callumrollo reviewed
Incorporating changes from @baileythegreen. Thanks for the improvements! Hopefully the simultaneous cross links will work

2021-03-04 16:07 UTC, baileythegreen approved these changes

2021-03-04 16:07 UTC, merged

2025-03-25 13:04 UTC, elletjies commented
@all-contributors please add @callumrollo for translation