Create Source Code, Execute, Queue New Terms
carpentries/glosario pull request #294
Opened 2021-03-22 01:52 UTC by sandyavila

Source code, is a human-readable text written in a specific programming language created by a programmer with the goal of setting exact rules for a computer-executable application.

Execute, is the process of running a computer software program, script, or command by reading and acting on the instructions converted into machine language.

Queue , is a data structure in which elements are removed in the same order they are entered (FIFO)- first-in first-out abstract data type used in computing.

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- 

## Language: 

- 

## Terms defined:

- 
- 
-

2021-03-22 11:05 UTC, baileythegreen commented
Hi @sandyavila,

So, a few comments (in case you plan to submit more things here—and I hope you do).

1. You should fill out the sections of the PR template, so that it looks something like this (no need to include the definitions here). :

<!-- If you are adding terms, change the pull request title to mention the terms added and language, or if there are a lot of them, the number of terms and language.

Examples:

Add definition for 'byte' (English)
Add definitions for 'agrégation', 'commentaire' (French)
Translate 5 terms (Spanish)
-->

> Fill in each of the sections (using NA for those that are not applicable).
> 
> ## Author: 
> 
> - @sandyavila 
> 
> ## Language: 
> 
> - English
> 
> ## Terms defined:
> 
> - source code
> - queue
> - execute


1. You haven't actually committed any changes. In order to do so you need to edit the `glossary.yml` file, either in the browser (which will open it in a new branch) or locally on your computer, using your favourite text editor. Then you have to commit the changes (in the browser, this involves clicking on 'Commit' at the bottom of the page; locally it's more involved and depends on if you are using the command line or the desktop application).

You can see no changes have been committed by looking at the 'Files changed' tab of this PR. It should look like this: https://github.com/carpentries/glosario/pull/282/files.

This link might help you get this working (clarifying how to commit and how to submit a pull request): https://guides.github.com/activities/hello-world/

2021-03-22 13:39 UTC, sandyavila commented
Thank you, Bailey for the updated details. I am pretty new to using GitHub and officially with creating Pull Requests. 😊

I had a feeling things weren’t posted correctly. I will go through this later today and fix it all and send any other questions or concerns I have in the process. But I hope that with the details you provide here, I can get it right this time. I very much appreciate your quick input and response!

Have a great Monday!

-Sandy

From: Bailey Harrington ***@***.***>
Sent: Monday, March 22, 2021 7:06 AM
To: carpentries/glosario ***@***.***>
Cc: Sandy Avila ***@***.***>; Mention ***@***.***>
Subject: Re: [carpentries/glosario] Create Source Code, Execute, Queue New Terms (#294)


Hi @sandyavila<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsandyavila&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367500686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kW%2BXcRHlUGw8CpHDFOp2RSmIqOB65BtzOwZeM6u6340%3D&reserved=0>,

So, a few comments (in case you plan to submit more things here—and I hope you do).

  1.  You should fill out the sections of the PR template, so that it looks something like this (no need to include the definitions here). :

Fill in each of the sections (using NA for those that are not applicable).

Author:

  *   @sandyavila<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsandyavila&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367510678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bv4c%2BFdeYIAxOJoxnRnnd%2FEzWCcRSUzNaAfqpeSHfNQ%3D&reserved=0>

Language:

  *   English

Terms defined:

  *   source code
  *   queue
  *   execute

  1.  You haven't actually committed any changes. In order to do so you need to edit the glossary.yml file, either in the browser (which will open it in a new branch) or locally on your computer, using your favourite text editor. Then you have to commit the changes (in the browser, this involves clicking on 'Commit' at the bottom of the page; locally it's more involved and depends on if you are using the command line or the desktop application).

You can see no changes have been committed by looking at the 'Files changed' tab of this PR. It should look like this: https://github.com/carpentries/glosario/pull/282/files<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarpentries%2Fglosario%2Fpull%2F282%2Ffiles&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367510678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HC3McXnaPEYcvWAyF2bDlU1DaMO33yIyKjk6nk%2Fg2q0%3D&reserved=0>.

This link might help you get this working (clarifying how to commit and how to submit a pull request): https://guides.github.com/activities/hello-world/<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fguides.github.com%2Factivities%2Fhello-world%2F&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367520674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=92Ois9fDpF5zrGeMd1BQzPsrnpCmdu%2F1Opbl4JokF90%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarpentries%2Fglosario%2Fpull%2F294%23issuecomment-803976485&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367520674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BIyTzPth7A%2BacMc6cpFPQFTXta%2BZEX%2FHNjZKHj4DQQI%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ35PHRN2BP6TUOVY5FJ3HDTE4P75ANCNFSM4ZSGJ75Q&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367530665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yGF%2FiCB47D6rN4ErwmUqwfmzYWfywcjdjpgTb3%2Bl9kI%3D&reserved=0>.

2021-03-30 20:40 UTC, sandyavila commented
Hi again, Bailey.

I am soo struggling through getting these terms to commit properly. I see the file and try to edit it but that option doesn't show up for me as an available option. I was able to put my code into comment which I hope you can see.

Any other kind of help you can provide would be greatly appreciated. I can meet you via Zoom to walk through steps if possible and thanks for your help in advance.

-Sandy

From: Bailey Harrington ***@***.***>
Sent: Monday, March 22, 2021 7:06 AM
To: carpentries/glosario ***@***.***>
Cc: Sandy Avila ***@***.***>; Mention ***@***.***>
Subject: Re: [carpentries/glosario] Create Source Code, Execute, Queue New Terms (#294)


Hi @sandyavila<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsandyavila&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367500686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kW%2BXcRHlUGw8CpHDFOp2RSmIqOB65BtzOwZeM6u6340%3D&reserved=0>,

So, a few comments (in case you plan to submit more things here-and I hope you do).

  1.  You should fill out the sections of the PR template, so that it looks something like this (no need to include the definitions here). :

Fill in each of the sections (using NA for those that are not applicable).

Author:

  *   @sandyavila<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsandyavila&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367510678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bv4c%2BFdeYIAxOJoxnRnnd%2FEzWCcRSUzNaAfqpeSHfNQ%3D&reserved=0>

Language:

  *   English

Terms defined:

  *   source code
  *   queue
  *   execute

  1.  You haven't actually committed any changes. In order to do so you need to edit the glossary.yml file, either in the browser (which will open it in a new branch) or locally on your computer, using your favourite text editor. Then you have to commit the changes (in the browser, this involves clicking on 'Commit' at the bottom of the page; locally it's more involved and depends on if you are using the command line or the desktop application).

You can see no changes have been committed by looking at the 'Files changed' tab of this PR. It should look like this: https://github.com/carpentries/glosario/pull/282/files<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarpentries%2Fglosario%2Fpull%2F282%2Ffiles&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367510678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HC3McXnaPEYcvWAyF2bDlU1DaMO33yIyKjk6nk%2Fg2q0%3D&reserved=0>.

This link might help you get this working (clarifying how to commit and how to submit a pull request): https://guides.github.com/activities/hello-world/<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fguides.github.com%2Factivities%2Fhello-world%2F&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367520674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=92Ois9fDpF5zrGeMd1BQzPsrnpCmdu%2F1Opbl4JokF90%3D&reserved=0>

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarpentries%2Fglosario%2Fpull%2F294%23issuecomment-803976485&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367520674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BIyTzPth7A%2BacMc6cpFPQFTXta%2BZEX%2FHNjZKHj4DQQI%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ35PHRN2BP6TUOVY5FJ3HDTE4P75ANCNFSM4ZSGJ75Q&data=04%7C01%7Csavila%40ucf.edu%7C37dde0e998304e07ce1608d8ed226af2%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637520079367530665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yGF%2FiCB47D6rN4ErwmUqwfmzYWfywcjdjpgTb3%2Bl9kI%3D&reserved=0>.

2021-03-30 20:46 UTC, baileythegreen commented
@sandyavila It looks like whatever you did last has managed to put the lines into the file successfully.

*However*, this is a glossary, and the entries need to be put into the file in alphabetical order. Please follow the same procedure you just did to get it to work, but cutting the lines from the end of the file and pasting them into the appropriate places.

2021-03-30 20:48 UTC, sandyavila commented
Got it! So that is all I had to do!? I am not sure how I figured it out but I am glad it worked. I will put them in alphabetical order. Thanks, Bailey!

From: Bailey Harrington ***@***.***>
Sent: Tuesday, March 30, 2021 4:47 PM
To: carpentries/glosario ***@***.***>
Cc: Sandy Avila ***@***.***>; Mention ***@***.***>
Subject: Re: [carpentries/glosario] Create Source Code, Execute, Queue New Terms (#294)


@sandyavila<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsandyavila&data=04%7C01%7Csavila%40ucf.edu%7Cc36e52e6e6974ab899e808d8f3bcf2c3%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637527340154019343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=j%2BPLirlrZ%2FglzU9GdE0N%2FgOw0k%2B5w9Uqo3rbhxtGguk%3D&reserved=0> It looks like whatever you did last has managed to put the lines into the file successfully.

However, this is a glossary, and the entries need to be put into the file in alphabetical order. Please follow the same procedure you just did to get it to work, but cutting the lines from the end of the file and pasting them into the appropriate places.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarpentries%2Fglosario%2Fpull%2F294%23issuecomment-810566580&data=04%7C01%7Csavila%40ucf.edu%7Cc36e52e6e6974ab899e808d8f3bcf2c3%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637527340154029336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7bz81ptItl7Ya18v6akvmU4auukaO8AbVY%2BtLAEd%2Bo8%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ35PHV3JAEJHGST4QW54NDTGI2DXANCNFSM4ZSGJ75Q&data=04%7C01%7Csavila%40ucf.edu%7Cc36e52e6e6974ab899e808d8f3bcf2c3%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637527340154029336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4IKq2rte0pwoXHQkMXnGu%2F6uqqIcvdiAT4wFNhiAzvE%3D&reserved=0>.

2021-03-30 20:51 UTC, baileythegreen commented
To be clear, once you have done that, I will then actually review the entries, and some code checks will be performed. Once the code checks clear, and I approve the content, it will be merged, but I sometimes request changes to the definitions, or to the formatting so that the code checks will pass.

2021-03-30 20:53 UTC, sandyavila commented
That is totally fine! I will look out for those messages and correct as requested. Thanks for ALL your help. I am fixing the alphabetical issues right now.

-Sandy

From: Bailey Harrington ***@***.***>
Sent: Tuesday, March 30, 2021 4:52 PM
To: carpentries/glosario ***@***.***>
Cc: Sandy Avila ***@***.***>; Mention ***@***.***>
Subject: Re: [carpentries/glosario] Create Source Code, Execute, Queue New Terms (#294)


To be clear, once you have done that, I will then actually review the entries, and some code checks will be performed. Once the code checks clear, and I approve the content, it will be merged, but I sometimes request changes to the definitions, or to the formatting so that the code checks will pass.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarpentries%2Fglosario%2Fpull%2F294%23issuecomment-810569580&data=04%7C01%7Csavila%40ucf.edu%7C5aee435091114e64ac0208d8f3bdada1%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637527343275704312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KkoATpMogWGsGKK3KP0bywE7pCCGM%2BZUpGHcplwEO0s%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ35PHRXGF27YSDS7EXC3WDTGI2XLANCNFSM4ZSGJ75Q&data=04%7C01%7Csavila%40ucf.edu%7C5aee435091114e64ac0208d8f3bdada1%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637527343275704312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5BDyEZ951SkQGcgB%2FFHCz9VwnZpCnJCVOf%2FLvsSKJws%3D&reserved=0>.

2021-03-31 16:43 UTC, baileythegreen commented on glossary.yml
> +     (FIFO)- first-in first-out abstract data type used in computing.
```suggestion
      (FIFO)- first-in first-out abstract data type used in computing.
```

2021-03-31 17:19 UTC, baileythegreen requested changes

2021-03-31 17:19 UTC, baileythegreen commented on glossary.yml
> +      with the goal of setting exact rules for a computer-executable application.
```suggestion
      Human-readable text written in a programming language 
      with the goal of setting exact rules for a computer-executable application.
```

I don't agree with the

> goal of setting exact rules for

bit; that sounds more like it refers to parameter settings than source code as a whole. The concept of source code as a series of actions is probably more useful. Also, the definition should reference the difference between source code and compiled code explicitly; likely in a second sentence. Right now, this is only implied by the words 'human-readable'.

2021-04-07 11:09 UTC, baileythegreen commented on glossary.yml
> +      with the goal of setting exact rules for a computer-executable application.
I don't agree with the

> goal of setting exact rules for

bit; that sounds more like it refers to parameter settings than source code as a whole. The concept of source code as a series of actions is probably more useful. Also, the definition should reference the difference between source code and compiled code explicitly; likely in a second sentence. Right now, this is only implied by the words 'human-readable'.

2021-04-07 11:10 UTC, baileythegreen requested changes
See inline comment.

2022-12-15 05:51 UTC, elletjies commented
Closing this pull request since the last activity took place in April 2021. Please feel free to reopen in the future to make the necessary changed.

2022-12-15 05:51 UTC, closed without merging