adds a translation of definition for package (Japanese)
carpentries/glosario pull request #299
Opened 2021-04-07 02:56 UTC by TomKellyGenetics

## Author: 

- @TomKellyGenetics 

## Language: 

- Japanese

## Terms defined:

- package (パッケージ)

2021-04-07 23:21 UTC, masamiy requested changes
Thanks heaps, @TomKellyGenetics ! You are truly awesome !!! Please see my suggestions.

2021-04-07 23:21 UTC, masamiy commented on glossary.yml
> +      それに、何かの言語の場合は「[ライブラリー](#library)」と「[モジュール](#module)」と読んでいのこと。
Suggestion: 「[ライブラリー](#library)」もしくは「[モジュール](#module)」と呼ぶプログラミング言語もある。

2021-04-07 23:21 UTC, masamiy commented on glossary.yml
> +      持つ関数のまとまりとデーターと文書化が分散して、再使えるように環境に加えること出来のこと。
Suggestion: 配布や再利用が可能なコード、データおよびドキュメントの集合体。

2021-04-08 03:47 UTC, TomKellyGenetics commented on glossary.yml
> +      それに、何かの言語の場合は「[ライブラリー](#library)」と「[モジュール](#module)」と読んでいのこと。
Thanks for the feedback. I think this better reflects the meaning of the English version. The terms aren't exclusive, different languages use "package", "library", "module", "plug-in", "add-on", "extension", etc.

```suggestion
      それに、プログラミング言語のパッケージも「[ライブラリー](#library)」や「[モジュール](#module)」と呼ぶもある。
```

2021-04-08 03:54 UTC, TomKellyGenetics commented on glossary.yml
> +      持つ関数のまとまりとデーターと文書化が分散して、再使えるように環境に加えること出来のこと。
This seems good to me. I've changed [Documentation](https://en.wikipedia.org/wiki/Documentation#Documentation_in_computer_science) to reflect the specific use in software field. Perhaps the Kanji wasn't clear for this usage.

```suggestion
      配布や再利用が可能なコード、データおよびソフトウェアドキュメンテーション集合体。
```

2021-04-14 22:38 UTC, naoe-tatara requested changes
I would suggest a small change in the second line :)

2021-04-14 22:38 UTC, naoe-tatara commented on glossary.yml
> +      それに、プログラミング言語のパッケージも「[ライブラリー](#library)」や「[モジュール](#module)」と呼ぶもある。
```suggestion
      プログラミング言語によっては、「[ライブラリー](#library)」や「[モジュール](#module)」と呼ぶこともある。
```

2021-04-15 12:41 UTC, TomKellyGenetics commented on glossary.yml
> +      それに、プログラミング言語のパッケージも「[ライブラリー](#library)」や「[モジュール](#module)」と呼ぶもある。
Thanks I think this works well. 🙂

2021-04-16 00:16 UTC, TomKellyGenetics commented
> Thanks I think this works well. 🙂
> 
> _Originally posted by @TomKellyGenetics in https://github.com/carpentries/glosario/pull/299#discussion_r614033508_

Thanks for your help @masamiy and @naoe-tatara. The Japanese translation seems ready to merge.

2021-04-17 07:50 UTC, masamiy commented on glossary.yml
> +      持つ関数のまとまりとデーターと文書化が分散して、再使えるように環境に加えること出来のこと。
I understand that documentation means documentation, e.g., README? I 'feel' 文書 is okay, but to make an emphasis on it is a document related to code and/or data, what about:
配布や再利用が可能なコード、データおよびそれらに付随する文書をひとまとまりにしたもの。
(Heavily plagiarised wiki -  https://ja.wikipedia.org/wiki/%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA)

2021-04-19 09:09 UTC, naoe-tatara approved these changes
Thanks @TomKellyGenetics !

2021-04-21 06:33 UTC, masamiy requested changes
Thank you for the contribution! I thought I did this one... may be in a wrong place? Anyhow, will you please have a look and let me know with your questions :)

2021-04-21 06:33 UTC, masamiy commented on glossary.yml
> +      配布や再利用が可能なコード、データおよびソフトウェアドキュメンテーション集合体。
Suggestion: 
配布や再利用が可能なコード、データおよびそれらに付随する文書をひとまとまりにしたもの。
or
 配布や再利用が可能なコード、データおよびそれらに付随する文書の集合体。

2021-04-21 06:33 UTC, masamiy commented on glossary.yml
> +      それに、プログラミング言語のパッケージも「[ライブラリー](#library)」や「[モジュール](#module)」と呼ぶもある。
Suggestion: 
[ライブラリー](#library)」や「[モジュール](#module)」と呼ぶプログラミング言語もある。

2021-04-21 09:01 UTC, naoe-tatara commented
Hi @masamiy , I think you see the outdated file. If you go to the "files changed" tab at the top, you will see already revised translations.

2021-04-21 23:08 UTC, masamiy commented
Thanks @naoe-tatara for navigating me to a right place. I think the first sentence needs to be changed a little still by at least adding 'の' before '集合体’. Am I looking at a right one??

2021-04-22 00:19 UTC, TomKellyGenetics commented on glossary.yml
> +      配布や再利用が可能なコード、データおよびソフトウェアドキュメンテーション集合体。
As mentioned above, I think ドキュメンテーション(documentation) is better for computer jargon. It seems to be used like this elsewhere in Japanese.

```suggestion
      配布や再利用が可能なコード、データおよびソフトウェアドキュメンテーションの集合体。
```

2021-04-22 00:21 UTC, TomKellyGenetics commented on glossary.yml
> +      配布や再利用が可能なコード、データおよびソフトウェアドキュメンテーション集合体。
To clarify, in this case "[documentation](https://en.wikipedia.org/wiki/Software_documentation)" means manuals and other files to guide users or developers.

2021-04-22 00:23 UTC, TomKellyGenetics commented on glossary.yml
> +      それに、プログラミング言語のパッケージも「[ライブラリー](#library)」や「[モジュール](#module)」と呼ぶもある。
This one's already taken care of in the current version 😃 

```
      プログラミング言語によっては、「[ライブラリー](#library)」や「[モジュール](#module)」と呼ぶこともある。
```

2021-04-22 00:29 UTC, TomKellyGenetics commented on glossary.yml
> +      持つ関数のまとまりとデーターと文書化が分散して、再使えるように環境に加えること出来のこと。
I still think ドキュメンテーション is more appropriate for this usage for example:
[https://ja.wikipedia.org/wiki/ソフトウェアドキュメンテーション](https://ja.wikipedia.org/wiki/%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%86%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3)
https://en.wikipedia.org/wiki/Software_documentation

2021-04-22 00:31 UTC, TomKellyGenetics commented
Thanks @masamiy, I've made grammatical changes as suggested but I think katakana for "documentation" is still more appropriate. https://github.com/carpentries/glosario/pull/299#discussion_r617980899

2021-04-22 08:50 UTC, naoe-tatara commented on glossary.yml
> +      持つ関数のまとまりとデーターと文書化が分散して、再使えるように環境に加えること出来のこと。
Yes, I agree with @TomKellyGenetics here. ドキュメンテーション is very often used and I think everyone who comes to the Carpentries workshop do understand what this means.

2021-04-22 22:44 UTC, masamiy approved these changes

2021-04-22 22:45 UTC, merged

2021-04-22 22:45 UTC, masamiy commented
All done. Thank you for the contribution.