Add definition for 'abstract method' (Spanish)
carpentries/glosario pull request #341
Opened 2021-07-16 13:45 UTC by manuGil

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

-  Manuel G. Garcia

## Language: 

- Spanish

## Terms defined:

- abstract method

2021-07-21 13:26 UTC, ian-flores approved these changes

2021-07-21 13:28 UTC, ian-flores requested changes

2021-08-24 22:24 UTC, nicoguaro commented on glossary.yml
> +    Programadores definen un método abstracto en una [superclase](#parent_class) para especificar operaciones
@manuGil, did you have an opportunity to check this?

2022-03-10 20:14 UTC, ian-flores approved these changes

2022-03-10 20:17 UTC, ian-flores approved these changes

2022-03-10 20:18 UTC, merged

2025-03-25 13:15 UTC, elletjies commented
@all-contributors please add @manuGil for translation