Add definition for 'ggplot2' (English)
carpentries/glosario pull request #357
Opened 2021-07-31 18:06 UTC by corybrunson

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Jason Cory Brunson

## Language: 

- English

## Terms defined:

- ggplot2

2021-08-09 16:02 UTC, zkamvar commented on glossary.yml
> +
```suggestion
```

2021-08-09 16:12 UTC, zkamvar requested changes
This looks good to me. Thank you!

Note that there might be some merge conflicts due to the editor deletions of trailing whitespace characters, but I should be able to address that before I merge.

2021-08-09 20:16 UTC, corybrunson commented
Oh my goodness, i'm sorry about that—i should have checked the `diff` before creating the PR. I'm glad to make a correction commit if it would make things more convenient on your end!

2021-08-09 23:38 UTC, zkamvar commented
> Oh my goodness, i'm sorry about that—i should have checked the `diff` before creating the PR. I'm glad to make a correction commit if it would make things more convenient on your end!

No worries! Part of the purpose of this repo is for demonstration and practise of git skills in a low-stakes environment, so these situations are perfectly normal and expected :smiley: The only thing I will ask is to click the "commit suggestion" button on my suggestion: https://github.com/carpentries/glosario/pull/357#discussion_r685325148

2021-08-09 23:57 UTC, corybrunson commented
Aha, thank you @zkamvar – that feature was new to me and i appreciate the lesson.

2021-08-10 00:10 UTC, zkamvar approved these changes

2021-08-10 00:10 UTC, merged