Translate function (German)
carpentries/glosario pull request #365
Opened 2021-08-12 12:32 UTC by cmeessen

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Christian Meeßen

## Language: 

- German

## Terms defined:

- function

2021-09-10 12:03 UTC, VScharf7 requested changes
line 2758: notwendige (typo)

2021-10-11 13:13 UTC, fmichonneau commented
@VScharf7 the error shown in the linting have just been fixed so it's ok to merge if you are happy with this PR. Thanks!

2021-11-02 12:53 UTC, cmeessen commented
@VScharf7 The typo has been fixed. If there is nothing else to be done, I'd be happy to see the PR merged. Thank you :)

2021-11-02 15:31 UTC, VScharf7 approved these changes

2021-11-02 15:31 UTC, merged