Add Japanese translation
carpentries/glosario pull request #379
Opened 2021-09-17 20:22 UTC by kozo2

Translate 2 terms (Japanese)

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- @kozo2

## Language: 

- Japanese

## Terms translated:

- operating_system
- filesystem

2021-09-21 22:41 UTC, masamiy requested changes
Thanks @kozo2 for your translation work. I made some comments as some expressions were a little colloquial (to me).

2021-09-21 22:41 UTC, masamiy commented on glossary.yml
> +      動作させるハードウェアがどんなものでも標準的なインターフェイスを提供するプログラム。
```suggestion
      動作させるハードウェアがどのようなものであっても標準的なインターフェイスを提供するプログラム。
```

2021-09-21 22:41 UTC, masamiy commented on glossary.yml
> +      オペレーティングシステムが動いているどんなコンピューターでも動かなければならない。
```suggestion
      そのオペレーティングシステムが搭載されているいかなるコンピューター上でも動作するはずである。
```

2021-09-21 22:41 UTC, masamiy commented on glossary.yml
> +      ファイルの保存方法と取得方法を管理する[オペレーティングシステム](#operating_system)の部分。
```suggestion
      [オペレーティングシステム](#operating_system)におけるファイルの保存方法と取得方法を管理する部分。
```

2021-09-23 03:29 UTC, kozo2 commented on glossary.yml
> +      また、それらすべてのファイルとディレクトリを参照するのに用いられるもの、
I will ask Carpentries Slack if there is a rule for it.

2021-09-23 13:25 UTC, naoe-tatara approved these changes
Thanks @kozo2 , I think the translation looks good :)

2021-09-24 10:30 UTC, fmichonneau commented
@masamiy could you please re-review and merge if you are happy with the changes? Thanks!

2021-09-28 00:30 UTC, merged

2025-03-31 14:48 UTC, elletjies commented
@all-contributors please add @kozo2  for translation