[German] add translations for algorithm, cpu and comment
carpentries/glosario pull request #380
Opened 2021-09-20 10:07 UTC by cosmofelix

## Author: 

- @cosmofelix

## Language: 

- de

## Terms defined:

- algorithm
- cpu
- comment

2021-11-02 15:29 UTC, VScharf7 requested changes
line 492: ... eindeutige, ausführbare **Abf**olge von Anweisungen...
line 1708: dienen der **Lesbarkeit**

2021-11-02 17:08 UTC, VScharf7 approved these changes

2021-11-02 20:41 UTC, VScharf7 requested changes
line 492

2021-11-02 20:41 UTC, VScharf7 commented on glossary.yml
> +      Ein Algorithmus beschreibt eine Handlungsvorschrift, ein Verfahren oder einen Regelsatz zum Lösen eines Problems. In der Informatik ist ein Algorithmus eine eindeutige, ausführbare Folge von An
line 492: eine eindeutige, ausführbare **Abf**olge

2021-11-02 20:41 UTC, VScharf7 commented on glossary.yml
> +      Anmerkungen in einem Programmcode oder Skript, die nicht vom Computer interpretiert oder ausgeführt werden. Kommentare dienen der Leserlichkeit und Dokumentation für Nutzer des Skripts. In viel
line 1708: dienen der **Lesbar**keit

2022-04-21 11:57 UTC, VScharf7 approved these changes

2022-04-22 19:03 UTC, fmichonneau commented
I notice that there are 2 definitions of "algorithm" in German now:

"      Ein Algorithmus ist in der Mathematik und der IT eine Vorgehensweise um
      Probleme zu lösen. Ein Algorithmus ist ein schrittweiser, eindeutiger
      Plan, oft in viele kleine Abschnitte unterteilt und mit Querverweisen
      ausgestattet, um ein spezifisches Problem zu lösen."

and

"Ein Algorithmus beschreibt eine Handlungsvorschrift, ein Verfahren oder einen Regelsatz zum Lösen eines Problems. In der Informatik ist ein Algorithmus eine eindeutige, ausführbare Folge von Anweisungen endlicher Länge zur Lösung eines Problems, welche immer das gleiche Ergebnis liefern."

Which one should we keep?

Thanks!

2022-11-16 14:07 UTC, zkamvar commented
> I notice that there are 2 definitions of "algorithm" in German now:
> 
> " Ein Algorithmus ist in der Mathematik und der IT eine Vorgehensweise um Probleme zu lösen. Ein Algorithmus ist ein schrittweiser, eindeutiger Plan, oft in viele kleine Abschnitte unterteilt und mit Querverweisen ausgestattet, um ein spezifisches Problem zu lösen."
> 
> and
> 
> "Ein Algorithmus beschreibt eine Handlungsvorschrift, ein Verfahren oder einen Regelsatz zum Lösen eines Problems. In der Informatik ist ein Algorithmus eine eindeutige, ausführbare Folge von Anweisungen endlicher Länge zur Lösung eines Problems, welche immer das gleiche Ergebnis liefern."
> 
> Which one should we keep?
> 
> Thanks!

Note for @glosario-editors-de, this is the reason the automated checks are failing. There can only be one definition

2022-11-16 14:47 UTC, VScharf7 commented
Hi there, 

the second is better if you ask me.

2022-11-16 15:23 UTC, zkamvar commented
> Hi there,
> 
> the second is better if you ask me.

Sounds good! I believe you should have the power to [edit the source file](https://github.com/cosmofelix/glosario/edit/cosmofelix-add-german/glossary.yml?pr=%2Fcarpentries%2Fglosario%2Fpull%2F380) and delete the outdated definition if you wish.

2022-11-17 08:59 UTC, VScharf7 approved these changes

2022-11-17 09:00 UTC, merged

2022-11-17 09:00 UTC, VScharf7 commented
Should be solved now :)

2025-03-31 14:46 UTC, elletjies commented
@all-contributors please add @cosmofelix  for translation