Update glossary.yml
carpentries/glosario pull request #452
Opened 2021-11-19 23:44 UTC by Mabrouk12300

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Mabrouk12300

## Language: 

- Arabic

## Terms defined:

- 
- 
-

2021-11-23 10:27 UTC, BatoolMM requested changes
ترجمة جدا ممتازة، الشئ الوحيد هو ان هذا 
YAML file 
لذلك الفراغ قبل بداية التريف مهم 
أيضا الروابط  والوصلات قد لاتعمل لذلك راح نتأكد لما ندمج البي آر لاحقا 

عذرا جدا على التأخر

2021-11-23 10:27 UTC, BatoolMM commented on glossary.yml
> +   دمج مجموعة من القيم في قيمة واحدة، مثال، حمع مجموعة من الأرقام
```suggestion
      دمج مجموعة من القيم في قيمة واحدة، مثال، حمع مجموعة من الأرقام
```

2021-11-23 10:30 UTC, BatoolMM requested changes

2021-11-23 10:30 UTC, BatoolMM commented on glossary.yml
> +  دالة تدمج العديد من القيم في قيمة واحدة ، مثل
```suggestion
     دالة تدمج العديد من القيم في قيمة واحدة ، مثل
```

2021-11-23 10:30 UTC, BatoolMM commented on glossary.yml
> +  [جمع](#sum)
```suggestion
     [جمع](#sum)
```

2021-11-23 10:30 UTC, BatoolMM commented on glossary.yml
> +  أو
```suggestion
     أو
```

2021-11-23 10:30 UTC, BatoolMM commented on glossary.yml
> +  [أقصى](#max).
```suggestion
     [أقصى](#max).
```

2021-11-23 10:30 UTC, BatoolMM commented on glossary.yml
> +   الخوارزمية عبارة عن مجموعة من الخطوات والمقدمات أوالقواعد التي يجب اتباعها لتحقيق مهمة معين.
```suggestion
      الخوارزمية عبارة عن مجموعة من الخطوات والمقدمات أوالقواعد التي يجب اتباعها لتحقيق مهمة معين.
```

2021-11-23 10:30 UTC, BatoolMM commented on glossary.yml
> +   في علوم الحاسب، الخوارزمية هي مجموعة من التعليمات في برنامج كمبيوتر تحل مشكلة حاسوبية.
```suggestion
      في علوم الحاسب، الخوارزمية هي مجموعة من التعليمات في برنامج كمبيوتر تحل مشكلة حاسوبية.
```

2021-11-23 10:30 UTC, BatoolMM commented on glossary.yml
> +   مجموعة من الوظائف والإجراءات التي توفرها مكتبات البرامج أو خدمة الويب والتي يمكن من خلالها  لتطبيق آخر التواصل معها.
```suggestion
      مجموعة من الوظائف والإجراءات التي توفرها مكتبات البرامج أو خدمة الويب والتي يمكن من خلالها  لتطبيق آخر التواصل معها.
```

2021-11-23 10:30 UTC, BatoolMM commented on glossary.yml
> +   واجهة التطبيق البرمجية ليست الكود أو قاعدة البيانات أو الخادم: إنها نقطة الوصول.
```suggestion
      واجهة التطبيق البرمجية ليست الكود أو قاعدة البيانات أو الخادم: إنها نقطة الوصول.
```

2021-11-23 10:30 UTC, BatoolMM commented on glossary.yml
> +    term: "أسكي"
```suggestion
    term: "آسكي"
```

2021-11-23 10:30 UTC, BatoolMM commented on glossary.yml
> +  طريقة قياسية لتمثيل الأحرف المستخدمة بشكل شائع في لغات أوروبا الغربية كأعداد صحيحة من 7 أو 8 بت،
```suggestion
     طريقة قياسية لتمثيل الأحرف المستخدمة بشكل شائع في لغات أوروبا الغربية كأعداد صحيحة من ٧ أو ٨ بت،
```

2021-11-23 10:30 UTC, BatoolMM commented on glossary.yml
> +   يحل محلها الآن   [الترميز الموحد] (#unicode).
```suggestion
      يحل محلها الآن   [الترميز الموحد] (#unicode).
```

2021-11-23 10:33 UTC, BatoolMM commented
Thank you for your contribution @Mabrouk12300 , just a few comments. Let me know if anything isn't clear! 

![](https://media3.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)

2021-12-02 15:13 UTC, BatoolMM requested changes

2021-12-02 15:13 UTC, BatoolMM commented on glossary.yml
> +   concatenando um conjunto de caracteres.
```suggestion
      concatenando um conjunto de caracteres.
```

2021-12-02 15:13 UTC, BatoolMM commented on glossary.yml
> +      la base de datos o el servidor; es el punto de acceso.
```suggestion
      la base de datos o el servidor; es el punto de acceso.    
```

2021-12-02 15:13 UTC, BatoolMM commented on glossary.yml
> +      voor te stel as 7- of 8-bis heelgetalle. ASCII word vervang deur [Unicode](#unicode).
```suggestion
      voor te stel as 7- of 8-bis heelgetalle. ASCII word vervang deur [Unicode](#unicode).
```

2021-12-02 15:13 UTC, BatoolMM commented on glossary.yml
> +      Asinchronies is die teenoorgestelde van sinchronies wat beteken dat twee of meer
```suggestion
      Asinchronies is die teenoorgestelde van sinchronies wat beteken dat twee of meer 
```

2021-12-02 15:13 UTC, BatoolMM commented on glossary.yml
> +      aktiwiteite tergelykertyd plaasvind. In programering is 'n asinchorniese bewerking 'n
```suggestion
      aktiwiteite tergelykertyd plaasvind. In programering is 'n asinchorniese bewerking 'n 
```

2021-12-02 15:13 UTC, BatoolMM commented on glossary.yml
> +      bewerking wat onafhanklik van 'n ander een plaasvind.
```suggestion
      bewerking wat onafhanklik van 'n ander een plaasvind.
```

2021-12-02 15:16 UTC, BatoolMM commented
It seems that the indentation of some of the text was changed when you added the Arabic translation, can you commit the changes I suggested and see if it fixes the CI?

2021-12-02 19:58 UTC, Mabrouk12300 commented
hi
Sure
I will do it now

[image: photo]
*Dr. Mabrouk boutagouga د. مبروك بوطقوقة *
أستاذ محاضر، جامعة باتنة 1 | المشرف العام لمركز فاعلون, رئيس تحرير مجلة
أنثروبولوجيا | مؤسس موقع أرنتروبوس

Whatsapp:(00213)5 <(00213)0669689110>50643288 | ***@***.***
***@***.***>

http://www.aranthropos.com | http://www. <http://www.fa3iloon.org>
fa3iloon.org <http://www.fa3iloon.org>
كلية اللغة والأدب العربي والفنون، جامعة باتنة 1، طريق بسكرة الجزائر 5000
<http://www.facebook.com/mabroukboutagouga> <http://Twitter.com/boutagouga>
<http://www.linkedin.com/in/mabrouk-boutagouga-44498a6a>


Le jeu. 2 déc. 2021 à 16:16, Batool Almarzouq ***@***.***> a
écrit :

> It seems that the indentation of some of the text was changed when you
> added the Arabic translation, can you commit the changes I suggested and
> see if it fixes the CI?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/carpentries/glosario/pull/452#issuecomment-984722794>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARWHGFS7Z7MKZ4OS323JJ2TUO6EVZANCNFSM5INHTVSQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2022-02-10 11:14 UTC, BatoolMM reviewed
I'm trying to review and fix for indentation

2022-02-10 11:14 UTC, BatoolMM commented on glossary.yml
> +  term: "دالة التجميع"
```suggestion
    term: "دالة التجميع"
```

2022-02-10 11:14 UTC, BatoolMM commented on glossary.yml
> +  def: >
```suggestion
    def: >
```

2022-02-10 11:14 UTC, BatoolMM commented on glossary.yml
> +   term: "خوارزمية"
```suggestion
     term: "خوارزمية"
```

2022-02-10 11:14 UTC, BatoolMM commented on glossary.yml
> +   def: >
```suggestion
     def: >
```

2022-02-10 11:19 UTC, BatoolMM commented on glossary.yml
> +   أو تحميع مجموعة من السلاسل.
```suggestion
     أو تحميع مجموعة من السلاسل. 
```

2022-02-10 11:19 UTC, BatoolMM commented on glossary.yml
> +     دالة تدمج العديد من القيم في قيمة واحدة ، مثل
```suggestion
       دالة تدمج العديد من القيم في قيمة واحدة ، مثل
```

2022-02-10 11:19 UTC, BatoolMM commented on glossary.yml
> +     [جمع](#sum)
```suggestion
       [جمع](#sum)
```

2022-02-10 11:19 UTC, BatoolMM commented on glossary.yml
> +     أو
```suggestion
       أو
```

2022-02-10 11:19 UTC, BatoolMM commented on glossary.yml
> +     [أقصى](#max).
```suggestion
       [أقصى](#max).
```

2022-02-10 11:19 UTC, BatoolMM commented on glossary.yml
> +   <span class="x x-first x-last">  </span>def: &gt;
```suggestion
    def: >
```

2022-02-10 11:19 UTC, BatoolMM commented on glossary.yml
> +
```suggestion
```

2022-02-10 11:19 UTC, BatoolMM commented on glossary.yml
> +     طريقة قياسية لتمثيل الأحرف المستخدمة بشكل شائع في لغات أوروبا الغربية كأعداد صحيحة من ٧ أو ٨ بت،
```suggestion
       طريقة قياسية لتمثيل الأحرف المستخدمة بشكل شائع في لغات أوروبا الغربية كأعداد صحيحة من ٧ أو ٨ بت،
```

2022-02-10 11:19 UTC, BatoolMM commented on glossary.yml
> +      يحل محلها الآن   [الترميز الموحد] (#unicode).
```suggestion
       يحل محلها الآن   [الترميز الموحد] (#unicode).
```

2022-02-10 11:30 UTC, BatoolMM commented on glossary.yml
> +     أو تحميع مجموعة من السلاسل.
```suggestion
```

2022-02-10 11:30 UTC, BatoolMM commented on glossary.yml
> +    def: >
```suggestion
   def: >
```

2022-02-10 11:35 UTC, BatoolMM commented on glossary.yml
> +   def: >
```suggestion
    def: >
```

2022-02-10 11:39 UTC, BatoolMM commented on glossary.yml
> +    term:"البيانات الضخمة"
```suggestion
    term: "البيانات الضخمة"
```

2022-02-20 10:37 UTC, BatoolMM commented
@fmichonneau Sorry but would you mind having a look at this! I tried to fix the white spaces/indentation but it's a bit challenging working with RTL in YAML - the CI for the lint still failing!!

<img src="https://media0.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy.gif"/>

2022-02-23 14:52 UTC, fmichonneau commented
Thanks @BatoolMM! it looks like the errors come from somewhere else in the file, so I'm going to merge this and fix the errors reported by the lintr.

2022-02-23 14:53 UTC, merged

2022-03-04 09:34 UTC, BatoolMM commented
Thank you @fmichonneau!

2025-03-31 13:59 UTC, elletjies commented
@all-contributors please add @Mabrouk12300 for translation

2025-04-10 09:22 UTC, elletjies commented
@all-contributors please add @BatoolMM for review, translation