Add definition of 'actual error' (Spanish)
carpentries/glosario pull request #470
Opened 2022-02-26 00:25 UTC by JorgeBornemann

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Jorge Bornemann

## Language: 

- Spanish

## Terms defined:

- actual error
- 
-

2022-02-26 21:16 UTC, JorgeBornemann commented
## Further definitions:
* expected_result
* pass_test
* fail_test

2022-03-10 20:16 UTC, ian-flores commented
@JorgeBornemann It seems like one of the terms is missing in the YAML file, can you take a look, please?

2022-03-10 20:17 UTC, ian-flores requested changes

2022-03-10 20:17 UTC, ian-flores commented on glossary.yml
> +      Una prueba falla si el [resultado real](#actual_result) no coincide con el [resultado esperado](#expected result).
It seems like the error is in this line. #expected_result should be the text

2022-03-10 21:38 UTC, JorgeBornemann commented
Sorry, typo missing underscore. corrected in commit [cbc2fbd](https://github.com/carpentries/glosario/pull/470/commits/cbc2fbdcc1fd4706342b2e498c77308051fccb27)

2022-03-21 02:32 UTC, ian-flores commented
Okay, fixed now, thank you!

2022-03-21 02:32 UTC, ian-flores approved these changes

2022-03-21 02:32 UTC, merged

2022-12-20 11:04 UTC, elletjies commented
@JorgeBornemann Thank you for contributing to Glosario in 2022! We are looking forward to receiving more PRs from you during 2023!