Update glossary file
carpentries/glosario pull request #513
Opened 2022-07-20 18:17 UTC by imanalhasani

translate the term "algorithmic bias" in line 636 to Arabic.

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- 

## Language: 

- 

## Terms defined:

- 
- 
-

2022-07-23 13:30 UTC, BatoolMM requested changes

2022-07-23 13:30 UTC, BatoolMM commented on glossary.yml
> +  term: " الخوارزمية المتحيزة"
```suggestion
    term: " الخوارزمية المتحيزة"
```

2022-07-23 13:31 UTC, BatoolMM commented
Hi Iman, 

Can you fill in the author, language and term in the description above, please? I also made a minor change for the space if you can approve it?

2022-07-23 19:00 UTC, imanalhasani commented
Hi Batool 
I added the requested info.

2022-07-23 19:07 UTC, imanalhasani reviewed
I approved the changes done by Batool.

2022-07-23 19:23 UTC, imanalhasani reviewed
The block mapping is filled.

2022-08-02 17:35 UTC, imanalhasani commented on glossary.yml
> +  term: " الخوارزمية المتحيزة"
```suggestion
  term: "الخوارزمية المتحيزة"
```

2022-08-02 17:36 UTC, imanalhasani commented on glossary.yml
> +  def: >
```suggestion
   def: >
```

2022-08-02 17:37 UTC, imanalhasani commented on glossary.yml
> +  النتائج المتكررة التي تظهر التحيز أو المعالجة المنحرفة ، الموجودة في [الخوارزمية] (# الخوارزمية).
```suggestion
  النتائج المتكررة التي تظهر التحيز أو المعالجة المنحرفة ، الموجودة في [الخوارزمية] (#الخوارزمية).
```

2022-08-03 14:24 UTC, BatoolMM commented
@imanalhasani 
الملف تغير وبعض المصطلحات تغير مكانها .. تحتاجي ترجعي بالزمن لل commit السابقة .. خلينا نشتغل مع بعض عليه في جلسة يوم الجمعة

2022-08-05 21:07 UTC, closed without merging

2022-10-11 06:56 UTC, imanalhasani commented
Hello Batool

I added the requested information but I can not tick on the approval option
when I review the changes. Sorry you I am new to Github.

Thanks

On Sat, Jul 23, 2022 at 5:31 PM Batool Almarzouq ***@***.***>
wrote:

> Hi Iman,
>
> Can you fill in the author, language and term in the description above,
> please? I also made a minor change for the space if you can approve it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/carpentries/glosario/pull/513#issuecomment-1193126302>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALTGSLPA4A7JJPIJA7ADME3VVPX45ANCNFSM54EU2TTA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-11 07:01 UTC, BatoolMM commented
Hi @imanalhasani , no worries at all.

This PR is closed since August, did you submit another PR recently?