Translate 21 terms (Spanish)
carpentries/glosario pull request #517
Opened 2022-08-02 09:31 UTC by dannda

## Author: 

- Daniela Basurto Lozada

## Language: 

- Spanish

## Terms defined:

- concatenate
- abstract method
- algorithmic bias
- argument
- arithmetic mean
- attribute
- backward compatible
- bug
- cache
- classification
- dictionary
- directory
- supervised learning
- true negative
- true positive
- unary expression
- unix
- unsupervised learning
- user interface
- vim
- virtual environment

2022-08-18 16:26 UTC, nicoguaro requested changes
There are some cross-references missing. Could you add them to the translation before we merge this PR?

2022-08-22 16:31 UTC, nicoguaro approved these changes

2022-08-22 16:50 UTC, merged

2022-12-20 10:56 UTC, elletjies commented
@dannda Thank you for contributing to Glosario in 2022! We are looking forward to receiving more PRs from you during 2023!

2025-03-31 09:59 UTC, elletjies commented
@all-contributors please add @dannda for translation