translate a term to Arabic
carpentries/glosario pull request #519
Opened 2022-08-06 14:35 UTC by imanalhasani

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

-  Iman Al Hasani

## Language: 

-  Arabic

## Terms defined:

-  algorithmic bias
- 
-

2022-08-08 15:44 UTC, BatoolMM commented on glossary.yml
> +    .[الخوارزمية](#algorithm) النتائج المتكررة التي تظهر التحيز أو المعالجة المنحرفة الموجودة في
```suggestion
     النتائج المتكررة التي تظهر التحيز أو المعالجة المنحرفة الموجودة في
    .[الخوارزمية(#algorithm)]
   
```

2022-08-08 18:11 UTC, BatoolMM requested changes

2022-08-08 18:11 UTC, BatoolMM commented on glossary.yml
> +
```suggestion
```

2022-08-08 18:11 UTC, BatoolMM commented on glossary.yml
> +       .على سبيل المثال، قد تعطي خوارزميات وسائل التواصل الاجتماعي الأولوية أو الوسم للمحتوى الخاص بمجموعات معينة من المستخدمين
```suggestion
     .على سبيل المثال، قد تعطي خوارزميات وسائل التواصل الاجتماعي الأولوية أو الوسم للمحتوى الخاص بمجموعات معينة من المستخدمين
```

2022-08-08 18:27 UTC, BatoolMM commented on glossary.yml
> +     .على سبيل المثال، قد تعطي خوارزميات وسائل التواصل الاجتماعي الأولوية أو الوسم للمحتوى الخاص بمجموعات معينة من المستخدمين
```suggestion
      .على سبيل المثال، قد تعطي خوارزميات وسائل التواصل الاجتماعي الأولوية أو الوسم للمحتوى الخاص بمجموعات معينة من المستخدمين
```

2022-08-08 18:27 UTC, BatoolMM commented on glossary.yml
> +     النتائج المتكررة التي تظهر التحيز أو المعالجة المنحرفة الموجودة في
```suggestion
      النتائج المتكررة التي تظهر التحيز أو المعالجة المنحرفة الموجودة في
```

2022-08-08 18:27 UTC, BatoolMM commented on glossary.yml
> +    .[الخوارزمية](#algorithm)
```suggestion
      .[الخوارزمية](#algorithm)
```

2022-08-08 18:30 UTC, BatoolMM commented
<img src="https://media4.giphy.com/media/3oz8xSXvzK6P9lNPby/giphy.gif"/>

The spaces are fixed, thank you @imanalhasani!

2022-08-08 18:30 UTC, BatoolMM approved these changes

2022-08-08 18:31 UTC, merged

2022-12-20 10:56 UTC, elletjies commented
@imanalhasani Thank you for contributing to Glosario in 2022! We are looking forward to receiving more PRs from you during 2023!

2025-03-31 09:55 UTC, elletjies commented
@all-contributors please add @imanalhasani for translation