Update glossary.yml
carpentries/glosario pull request #524
Opened 2022-08-21 12:12 UTC by Taghreed-A

add the translations (in Arabic) of the terms confidence interval, constant, and correlation.

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- 

## Language: 

- 

## Terms defined:

- 
- 
-

2022-08-21 12:14 UTC, Taghreed-A commented
add the translations (in Arabic) of the terms confidence interval, constant, and correlation.

2022-08-22 15:06 UTC, BatoolMM requested changes

2022-08-22 15:06 UTC, BatoolMM commented on glossary.yml
> +    فترة الثقة تتكون من التقدير المعلمة وهامش الخطأ, وهي الفترة التي نثق بأن قيمة التقدير تكون داخل هذه الفترة
```suggestion
      فترة الثقة تتكون من التقدير المعلمة وهامش الخطأ, وهي الفترة التي نثق بأن قيمة التقدير تكون داخل هذه الفترة
```

2022-08-22 15:06 UTC, BatoolMM commented on glossary.yml
> +    فترة الثقة تتكون من التقدير المعلمة وهامش الخطأ, وهي الفترة التي نثق بأن قيمة التقدير تكون داخل هذه الفترة
Can you fix this space?

2022-08-22 15:22 UTC, BatoolMM commented
<img src="https://media4.giphy.com/media/qyHTlb1MIkMP0ZWZFy/giphy.gif"/>

يعطيك العافية!

2022-08-22 15:22 UTC, BatoolMM approved these changes

2022-08-22 15:22 UTC, merged

2022-12-20 10:54 UTC, elletjies commented
Thank you for contributing to Glosario in 2022! We are looking forward to receiving more PRs from you during 2023!

2025-03-31 09:47 UTC, elletjies commented
@all-contributors please add @Taalmasoud for translation