traduccionn to Spanish
carpentries/glosario pull request #625
Opened 2024-02-29 15:02 UTC by yabellini

## Author: 

-  yabellini

## Language: 

-  Spanish

## Terms defined:

- epoch
- learning rate
-

2024-03-01 03:49 UTC, nicoguaro commented on glossary.yml
> +      En [deep learning](#deep_learning), un epoch es un ciclo completo en el proceso del aprendizaje profundo
Here we are using "deep learning" and "aprendizaje profundo" at the same time. Should we keep just "aprendizaje profundo"?

2024-03-01 03:49 UTC, nicoguaro requested changes
I think that we should use "aprendizaje profundo" instead of "deep learning" in Spanish

2024-03-02 02:18 UTC, yabellini reviewed
Cambios hechos de acuerdo al pedido de la revision.  Gracias @nicoguaro !

2024-03-02 02:18 UTC, yabellini commented on glossary.yml
> +    term: epoch (deep learning)
```suggestion
    term: epoch (aprendizaje profundo)
```

2024-03-02 02:18 UTC, yabellini commented on glossary.yml
> +      En [deep learning](#deep_learning), un epoch es un ciclo completo en el proceso del aprendizaje profundo
```suggestion
      En [aprendizaje profundo](#deep_learning), un epoch es un ciclo completo en el proceso del aprendizaje profundo 
```

2024-03-02 02:18 UTC, yabellini commented on glossary.yml
> +    term: tasa de aprendizaje (deep learning)
```suggestion
    term: tasa de aprendizaje (aprendizaje profundo)
```

2024-05-09 05:24 UTC, elletjies commented
@nicoguaro Could you check the changes to the translation again please?

2024-05-16 19:31 UTC, nicoguaro approved these changes

2024-05-16 19:32 UTC, merged

2024-05-17 05:19 UTC, elletjies commented
@nicoguaro thank you for the review!