Translate some ML terms to Spanish
carpentries/glosario pull request #626
Opened 2024-02-29 15:04 UTC by paocorrales

## Author: 

- Pao Corrales 

## Language: 

- Spanish

## Terms defined:

- Hidden layer
- ROC curve

2024-03-01 03:42 UTC, nicoguaro commented on glossary.yml
> +      no puedes observadirectamente el ingreso y salida de valores.
There is an r and space missing here

2024-03-01 03:44 UTC, nicoguaro commented on glossary.yml
> +      es un gráfico que muestra el desempeño de un clasificador binario con diferentes umbrales de [classificación](#classification)
"classificación" should be "clasificación"

"Sensitividad" should be "Sensibilidad"

"taza" should be "tasa"

2024-03-01 03:44 UTC, nicoguaro requested changes
There are some minor mistakes in the translation

2024-04-08 03:41 UTC, paocorrales commented on glossary.yml
> +      no puedes observadirectamente el ingreso y salida de valores.
```suggestion
      no puedes observar directamente el ingreso y salida de valores.
```

2024-04-08 03:41 UTC, paocorrales commented on glossary.yml
> +      es un gráfico que muestra el desempeño de un clasificador binario con diferentes umbrales de [classificación](#classification)
```suggestion
      es un gráfico que muestra el desempeño de un clasificador binario con diferentes umbrales de [clasificación](#classification)
```

2024-04-08 03:41 UTC, paocorrales commented on glossary.yml
> +      La curva se obtiene graficando la taza de verdaderos positivos (también conocida como Recall o [Sensitividad](#sensitivity))
```suggestion
      La curva se obtiene graficando la tasa de verdaderos positivos (también conocida como Recall o [Sensibilidad](#sensitivity))
```

2024-05-09 05:24 UTC, elletjies commented
@nicoguaro  Could you check the changes to the translation again please?

2024-05-16 19:34 UTC, nicoguaro approved these changes

2024-05-16 19:35 UTC, merged

2024-05-17 05:18 UTC, elletjies commented
@nicoguaro thank you for the review!

2025-03-31 08:34 UTC, elletjies commented
@all-contributors please add @paocorrales for translation