Add Ukrainian description of Glosario
carpentries/glosario pull request #642
Opened 2024-05-15 15:50 UTC by olexandr-konovalov

Translation of the text for the Glosario front page.

Please don't merge until it will be reviewed within the Ukrainian translators community.

2024-05-31 08:31 UTC, ViktoriiaGrivina approved these changes
All is good. Approved.

2024-06-03 09:57 UTC, olexandr-konovalov commented
@ViktoriiaGrivina thank you for your first review :)

2024-06-03 23:20 UTC, olexandr-konovalov commented on _config.yml
> +    name: Ukrainian
@ViktoriiaGrivina was looking at https://glosario.carpentries.org/ - in the list of languages on the right we have native language names, so we need to replace Ukrainian -> "Українська мова" або "Українська". Any preferences?

2024-06-08 11:19 UTC, olexandr-konovalov commented on _config.yml
> +    name: Ukrainian
Had a look at some examples of glossaries online - one word "Українська" would be consistent.

2024-06-08 11:22 UTC, olexandr-konovalov commented
@ViktoriiaGrivina made some more changes - just in case, could you please have another look? Thanks.

2024-06-08 11:51 UTC, Herobread requested changes

2024-06-08 11:51 UTC, Herobread commented on _config.yml
> +      на терміни та їх означення на різних мовах.
Не критично, але [визначення](https://slovnyk.ua/index.php?swrd=%D0%B2%D0%B8%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%BD%D1%8F) буде краще, ніж [означення](https://slovnyk.ua/index.php?swrd=%D0%BE%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%BD%D1%8F) у цьому контексті.

2024-06-08 12:03 UTC, olexandr-konovalov commented on _config.yml
> +      на терміни та їх означення на різних мовах.
Цілком згоден, дякую!

2024-06-08 12:06 UTC, Herobread approved these changes

2024-06-10 11:20 UTC, olexandr-konovalov commented
@elletjies could you please also merge this - I think we can't see an overview page otherwise.

@ViktoriiaGrivina in case of any further changes, we will incorporate them later.

2024-06-10 11:22 UTC, elletjies approved these changes

2024-06-10 11:22 UTC, merged