Translating "string" into Ukrainian
carpentries/glosario pull request #651
Opened 2024-06-02 21:20 UTC by olexandr-konovalov

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Olexandr Konovalov

## Language: 

- Ukrainian

## Terms defined:

- string
- 
-

2024-06-08 10:52 UTC, Herobread approved these changes

2024-06-08 11:50 UTC, olexandr-konovalov commented
Oops, accidentally deleted the branch - restored. Should have more informative branch name (what I usually do when I use Git locally, but this was a demo of the web-interface).

2024-06-08 17:29 UTC, Dod900ls1 requested changes

2024-06-08 17:29 UTC, Dod900ls1 commented on glossary.yml
> +    term: "рядок"
Можна замінити "з текстом" на "тексту": Це робить визначення більш чітким.

2024-06-08 17:29 UTC, Dod900ls1 commented on glossary.yml
> +      У мовах програмування - блок з текстом, тобто послідовність символів.
В кінці можна додати "яка використовується для зберігання та маніпуляції текстовими даними": Це додає більше контексту і пояснює призначення рядка.

`У мовах програмування — блок тексту, тобто послідовність символів, яка використовується для зберігання та маніпуляції текстовими даними.`

2024-06-08 17:30 UTC, Dod900ls1 commented on glossary.yml
> +    term: "рядок"
Sorry, indicated the wrong row. It meant to be a row number 837

2024-06-08 19:41 UTC, olexandr-konovalov commented on glossary.yml
> +      У мовах програмування - блок з текстом, тобто послідовність символів.
@Dod900ls1 done - please review

2024-06-11 13:31 UTC, Dod900ls1 approved these changes
LGTM

2024-06-11 15:46 UTC, elletjies approved these changes

2024-06-11 15:46 UTC, merged