Translated API to Ukrainian
carpentries/glosario pull request #654
Opened 2024-06-04 17:21 UTC by Dod900ls1

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

-  Yehor Boiar

## Language: 

- Ukrainian

## Terms defined:

- API

2024-06-04 18:14 UTC, olexandr-konovalov commented on glossary.yml
> +  en:
should be "uk"

2024-06-04 18:53 UTC, olexandr-konovalov commented on glossary.yml
> +  en:
As README at https://github.com/carpentries/glosario says, this "must be a single ISO 639 language code" and for Ukrainian language that is "uk"

2024-06-05 13:33 UTC, olexandr-konovalov commented
@Dod900ls1 why to close this? If you use Git locally, it's easy to update the PR. You need to change to your branch, edit the file, commit changes. The PR will be updated automatically with a new "fixup" commit. Even better, instead of this, you can also amend the existing commit, and the force-push it _to your feature branch in your fork_

2024-06-05 13:49 UTC, Dod900ls1 commented
I closed it accidentaly. I tried to rename a branch and it have got deleted in the process, so PR closed automatically. Sorry!

2024-06-08 10:48 UTC, Herobread approved these changes

2024-06-11 20:39 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Інтерфейс Програмування Додатків (API)"
додатків -> застосунків

Варто пошукати інші переклади та порівняти:
- прикладний програмний інтерфейс
- інтерфейс прикладного програмування

тощо

2024-06-14 10:46 UTC, Dod900ls1 commented on glossary.yml
> +      через які інший додаток може з нею взаємодіяти. API – це не код, база даних чи
Good call!

2024-06-20 07:47 UTC, YehorBoiar commented
@Herobread @VeronikaShevc Please review

2024-06-20 12:57 UTC, VeronikaShevc approved these changes

2024-06-20 18:31 UTC, YehorBoiar commented on glossary.yml
> +    term: "Інтерфейс Програмування Застосунків (API)"
No, because acronym

2024-06-20 18:43 UTC, Herobread commented on glossary.yml
> +    term: "Інтерфейс Програмування Застосунків (API)"
oright meh

2024-06-20 19:19 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Інтерфейс Програмування Застосунків (API)"
Not really: see https://abbrs.info/ - I think @Herobread is right

2024-06-20 21:58 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Інтерфейс Програмування Застосунків (API)"
@YehorBoiar so one more change, and we will merge this one! It's currently the oldest still open PR among Ukrainian translations

2024-06-21 21:02 UTC, olexandr-konovalov requested changes
@YehorBoiar one more fix (lowercase) and then this will be ready (submitting this via "review" tool so it will be properly displayed with the "changes requested" status.

2024-06-22 08:19 UTC, YehorBoiar commented
@olexandr-konovalov done!

2024-06-22 08:30 UTC, olexandr-konovalov approved these changes
Thanks @YehorBoiar! @elletjies please merge

2024-06-24 16:40 UTC, merged