Translated "ASCII" to Ukrainian
carpentries/glosario pull request #659
Opened 2024-06-06 17:09 UTC by Dod900ls1

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Yehor Boiar

## Language: 

- Ukrainian

## Terms defined:

- ASCII

2024-06-06 17:20 UTC, olexandr-konovalov requested changes
@Dod900ls1 Now this PR also includes commit from PR #658. This is not correct. When you create a feature branch, you had to first switch back to `main` by calling `git checkout main`, then pull changes from upstream (always a good idea), then call `git checkout -b ASCII` to create a new branch.

I suggest to leave this as is for now, and will fix this in another call. When you will create a new branch for another term, remember doing it from `main`.

See also the workflow in the contributor's guide to Glosario in its README: it uses web-based VSCode, but also first goes to `main` and creates a new branch off `main`.

2024-06-06 17:21 UTC, olexandr-konovalov commented
@Dod900ls1 I've noticed now that you've edited your PR faster than I wrote my comment :) well done!

2024-06-06 17:22 UTC, olexandr-konovalov commented on glossary.yml
> +
@Dod900ls1 another new line - not needed

2024-06-08 10:36 UTC, Herobread approved these changes

2024-06-12 12:34 UTC, Dod900ls1 commented on glossary.yml
> +      Зараз замінений [Unicode](#unicode).
замінений на [Unicode] відчуваєтся більш природньо. Виправив на цей варіант

2024-06-12 17:23 UTC, olexandr-konovalov approved these changes
@elletjies please merge

2024-06-12 19:46 UTC, merged