Translate "GPU" into Ukrainian
carpentries/glosario pull request #664
Opened 2024-06-08 16:52 UTC by Herobread

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Oleksii Nazarenko

## Language: 

- Ukrainian

## Terms defined:

- GPU

2024-06-08 17:35 UTC, Dod900ls1 requested changes
Overall, looks good, but have one suggestion.

2024-06-08 17:35 UTC, Dod900ls1 commented on glossary.yml
> +      розроблений для використання у графіці, але також використовується
Можна змінити "у графіці" на "обробки графіки": Це робить фразу більш конкретною.

2024-06-08 17:36 UTC, Dod900ls1 commented on glossary.yml
> +      розроблений для використання у графіці, але також використовується
`Спеціалізований процесор, призначений для паралельного виконання багатьох екземплярів однієї програми. Спочатку розроблений для обробки графіки, але також використовується для загальних обчислень у вигляді [обчислювальних шейдерів](https://github.com/carpentries/glosario/pull/664#compute_shader).`

2024-06-09 10:40 UTC, Dod900ls1 approved these changes
LGTM

2024-06-09 14:11 UTC, olexandr-konovalov commented on glossary.yml
> +      виконання багатьох екземплярів однієї програми. Спочатку
Мабуть "екземплярів" -> "копій"?

2024-06-09 14:11 UTC, olexandr-konovalov commented on glossary.yml
> +      розроблений для обробки графіки, але також використовується
мабуть "але зараз також" ?

2024-06-09 20:33 UTC, Herobread commented
Оновив

2024-06-09 20:51 UTC, olexandr-konovalov commented on glossary.yml
> +      розроблений для обробки графіки, але також використовується
@Herobread але "використовується" при оновленні зникло - це випадково?

2024-06-09 20:55 UTC, Herobread commented on glossary.yml
> +      розроблений для обробки графіки, але також використовується
так, вибачайте, зараз виправлю

2024-06-10 20:18 UTC, olexandr-konovalov commented on glossary.yml
> +    acronym: "ГП"
@Herobread we did not translate acronym for JSON in #655. Is "ГП" widely used in Ukrainian sources? Would it actually be more helpful to the reader if we keep "GPU"?

2024-06-10 21:13 UTC, Herobread commented on glossary.yml
> +    acronym: "ГП"
I agree, GPU is more popular option than ГП and this would be better for consistency.

2024-06-11 08:29 UTC, olexandr-konovalov approved these changes
@elletjies this is ready to merge too, thanks!

2024-06-11 10:16 UTC, elletjies approved these changes

2024-06-11 10:16 UTC, merged

2024-06-11 20:25 UTC, olexandr-konovalov commented on glossary.yml
> +  uk:
@Herobread checked rendered version at https://glosario.carpentries.org/uk/#gpu - both English and Ukrainian have wrong hyperlink formatting - the 2nd pair of brackets must be `(...)` 

Would you like to submit a PR to fix both?

2025-03-31 08:26 UTC, elletjies commented
@all-contributors please add @Herobread for translation