Translate "JSON" to Ukrainian
carpentries/glosario pull request #665
Opened 2024-06-08 17:06 UTC by Herobread

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Oleksii Nazarenko

## Language: 

- Ukrainian

## Terms defined:

- JSON

2024-06-08 17:42 UTC, Dod900ls1 requested changes

2024-06-08 17:42 UTC, Dod900ls1 commented on glossary.yml
> +    term: "Нотація об'єктів JavaScript"
We can add (JSON) in the end of term to refer to it in the definition. 

`Нотація об'єктів JavaScript (JSON)`

2024-06-08 17:42 UTC, Dod900ls1 commented on glossary.yml
> +      символів, у структурах [списки](#list) та [ключ/значення](#dictionary). Ця абревіатура
You mention some acronym on this row, but it's not clear what acronym do you mean unless you know the term.

2024-06-08 17:55 UTC, Herobread commented on glossary.yml
> +      символів, у структурах [списки](#list) та [ключ/значення](#dictionary). Ця абревіатура
Замінив "Ця абревіатура" на "JSON"

2024-06-08 17:57 UTC, Herobread commented on glossary.yml
> +    term: "Нотація об'єктів JavaScript"
В інших мовах не додавали і є поле `acronym: "JSON"`, тому не буду додавати до `term`

2024-06-08 18:58 UTC, olexandr-konovalov requested changes

2024-06-08 18:58 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Нотація об'єктів JavaScript"
Good to spot the `acronym: "JSON"` field - please also add it here like in other languages

2024-06-08 18:58 UTC, olexandr-konovalov commented on glossary.yml
> +      розшифровується як «JavaScript Object Notation»; на відміну від більш чітко визначених
Please do not use "fancy quotes" - use `"JavaScript Object Notation"` (you can prevent auto-conversion in your editor or operating system settings)

2024-06-08 21:35 UTC, olexandr-konovalov approved these changes

2024-06-09 10:39 UTC, Dod900ls1 approved these changes
All good.

2024-06-09 15:17 UTC, olexandr-konovalov requested changes

2024-06-09 15:17 UTC, olexandr-konovalov commented on glossary.yml
> +      Спосіб представлення даних шляхом поєднання базових значень, таких як числа та рядки
- поєднання звучить, як переклад слова "concatenation" - мабуть, щось інше?
- мабуть "базових значень" -> "значень у базових форматах"?
- "у структурах [списки](#list) та [ключ/значення]" не дуже гарно звучить
- "вона не обтяжена" - хто "вона"? мабуть "цей формат"?
- "вона не обтяжена" -> "цей формат не ускладнений"

2024-06-11 09:03 UTC, Herobread commented on glossary.yml
> +      Спосіб представлення даних шляхом поєднання базових значень, таких як числа та рядки
Updated

2024-06-11 09:06 UTC, olexandr-konovalov commented on glossary.yml
> +      Спосіб представлення даних шляхом поєднання базових значень, таких як числа та рядки
Виглядає добре, але ж тепер "таких як" використовується три рази - можна якось цього запобігти?

2024-06-11 16:54 UTC, Herobread commented on glossary.yml
> +      Спосіб представлення даних шляхом поєднання базових значень, таких як числа та рядки
Так, оновив

2024-06-11 17:01 UTC, olexandr-konovalov commented on glossary.yml
> +      Спосіб представлення даних шляхом комбінування значень у базових форматах: числа та рядки
Це краще! Все же якось після двокрапки не зрозуміло де закінчується блок тексту. А як щодо 

у базових форматах (числа, рядки символів тощо) у структурах ...

2024-06-11 18:37 UTC, Herobread commented on glossary.yml
> +      Спосіб представлення даних шляхом комбінування значень у базових форматах: числа та рядки
згоден

2024-06-11 20:00 UTC, olexandr-konovalov commented on glossary.yml
> +      символів, тощо) у структурах даних, таких як [списки](#list) та [словники](#dictionary). JSON
здається, що перед тощо кома не ставиться

2024-06-12 08:40 UTC, Herobread commented on glossary.yml
> +      символів, тощо) у структурах даних, таких як [списки](#list) та [словники](#dictionary). JSON
@olexandr-konovalov  [так](https://onlinecorrector.com.ua/uk/%D0%B7%D0%B0%D0%B9%D0%B2%D0%B0-%D0%BA%D0%BE%D0%BC%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4-%D1%82%D0%BE%D1%89%D0%BE/), оновив

2024-06-12 17:16 UTC, olexandr-konovalov commented on glossary.yml
> +      стандартів, наприклад, [XML](#xml), цей формат не обтяжений синтаксисом для коментарів
"не обтяжений" чи "не ускладнений" - які будуть думки @Herobread ?

2024-06-12 21:53 UTC, Herobread commented on glossary.yml
> +      стандартів, наприклад, [XML](#xml), цей формат не обтяжений синтаксисом для коментарів
згоден, [ускладнений](https://slovnyk.ua/index.php?swrd=%D1%83%D1%81%D0%BA%D0%BB%D0%B0%D0%B4%D0%BD%D0%B5%D0%BD%D0%B8%D0%B9#:~:text=%D0%A1%D0%BA%D0%BB%D0%B0%D0%B4%D0%BD%D1%96%D1%88%D0%B8%D0%B9%2C%20%D0%BD%D1%96%D0%B6%20%D0%B7%D0%B2%D0%B8%D1%87%D0%B0%D0%B9%D0%BD%D0%BE%2C%20%D0%BD%D1%96%D0%B6%20%D1%96%D0%BD%D1%88%D0%B8%D0%B9.) краще, ніж [обтяжений](https://slovnyk.ua/index.php?swrd=%D0%BE%D0%B1%D1%82%D1%8F%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9)

2024-06-13 05:19 UTC, Dod900ls1 requested changes
One small suggestion, but, generally LGTM.

2024-06-13 05:19 UTC, Dod900ls1 commented on glossary.yml
> +      символів тощо) у структурах даних, таких як [списки](#list) та [словники](#dictionary). JSON
"(числа, рядки символів тощо)"  - наче правильніше ніж "(числа та рядки символів тощо)"

2024-06-13 07:08 UTC, olexandr-konovalov commented on glossary.yml
> +      символів тощо) у структурах даних, таких як [списки](#list) та [словники](#dictionary). JSON
+1

2024-06-13 08:47 UTC, Herobread commented on glossary.yml
> +      символів тощо) у структурах даних, таких як [списки](#list) та [словники](#dictionary). JSON
@Dod900ls1 updated

2024-06-13 17:12 UTC, olexandr-konovalov approved these changes
@elletjies please merge

2024-06-13 17:37 UTC, merged