Translate "Absolute Path" to Ukrainian
carpentries/glosario pull request #666
Opened 2024-06-08 17:11 UTC by Herobread

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Oleksii Nazarenko

## Language: 

- Ukrainian

## Terms defined:

- Absolute Path

2024-06-08 17:46 UTC, Dod900ls1 requested changes

2024-06-08 17:46 UTC, Dod900ls1 commented on glossary.yml
> +      незалежно від того, де він обчислюється. Абсолютний шлях є еквівалентом
Можна замінити "де він обчислюєтся" на "поточного розташування". Це робить визначення трохи простішим і зрозумілішим, видаляючи зайве слово "обчислюється"

`Шлях, який вказує на те саме місце у [файловій системі](#filesystem) незалежно від поточного розташування. Абсолютний шлях є еквівалентом широти та довготи в географії.`

2024-06-08 17:51 UTC, Herobread commented on glossary.yml
> +      незалежно від того, де він обчислюється. Абсолютний шлях є еквівалентом
Згоден, оновив

2024-06-09 07:48 UTC, ViktoriiaGrivina commented
All good.

2024-06-09 10:38 UTC, Dod900ls1 approved these changes
Well done.

2024-06-09 15:01 UTC, olexandr-konovalov commented on glossary.yml
> +      Шлях, який вказує на те саме місце у [файловій системі](#filesystem)
Мабуть "одне й теж саме" ?

2024-06-09 15:01 UTC, olexandr-konovalov commented on glossary.yml
> +      еквівалентом широти та довготи в географії.
Не дуже впевнений, але мені здається "аналогом" тут буде краще, ніж "еквівалентом".

2024-06-11 20:28 UTC, olexandr-konovalov requested changes
@Herobread some comments are still unresolved

2024-06-12 08:38 UTC, Herobread commented
@olexandr-konovalov updated

2024-06-12 17:12 UTC, olexandr-konovalov approved these changes
@elletjies please merge

2024-06-12 19:45 UTC, merged