Translated "SSH" and "SSH key" to Ukrainian
carpentries/glosario pull request #667
Opened 2024-06-09 11:20 UTC by Dod900ls1

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Yehor Boiar 

## Language: 

- Ukrainian

## Terms defined:

- SSH
- SSH key

2024-06-09 11:31 UTC, Herobread requested changes

2024-06-09 11:31 UTC, Herobread commented on glossary.yml
> +      частину можна безпечно ділитися, але якщо приватна частина стає відомою, ключ вважається скомпрометованим.
Заміни [ділитися](https://slovnyk.ua/index.php?swrd=%D0%B4%D1%96%D0%BB%D0%B8%D1%82%D0%B8%D1%81%D1%8F) на [поширювати](https://slovnyk.ua/index.php?swrd=%D0%BF%D0%BE%D1%88%D0%B8%D1%80%D1%8E%D0%B2%D0%B0%D1%82%D0%B8)

Ділитися означає split, a поширювати - share

2024-06-09 11:43 UTC, Dod900ls1 commented on glossary.yml
> +      частину можна безпечно ділитися, але якщо приватна частина стає відомою, ключ вважається скомпрометованим.
Changed

2024-06-09 11:44 UTC, Herobread approved these changes

2024-06-09 12:02 UTC, ccoVeille commented
Hi @Dod900ls1 

I'm a random guy who watches the repository.

While I see as a good thing that you are adding translations, I'm surprised you are not grouping them.

I mean you are adding them one by one, every few days.

2024-06-09 12:27 UTC, ccoVeille commented
I mean, this is a bit noisy

![Screenshot_20240609_142705_GitHub.jpg](https://github.com/carpentries/glosario/assets/3875889/9736c990-a459-440d-8380-6582bed16d8c)

2024-06-09 13:18 UTC, Dod900ls1 commented
@ccoVeille Good point.

2024-06-11 13:37 UTC, olexandr-konovalov commented
@ccoVeille sorry for lots of notifications - we have a translation sprint in June-July, so there may be quite a few more coming shortly. Please note this if you'd like to adjust your watching preferences for these two months. The repository has both examples of PR for a single word and for multiple terms, and Glosario maintainers are happy with us doing it that way. OTOH, we plan to review and merge PRs quickly, so they will disappear from the list of open PRs, reducing the noise.

One thought that I have against mixing many words in one PR - if you have commit A for word X, and then later commit B for word Y, you can't fix the commit A by `--amend` anymore, as it's not the latest. You can of course, use `git rebase -i` to refactor the history, and rewrite older commits, but that require more advanced skills - not every contributor is well versed with these commands yet...

2024-06-11 14:13 UTC, ccoVeille commented
Thanks for giving context in your detailed reply.

I think I will adjust my settings, yes

2024-06-11 15:03 UTC, olexandr-konovalov requested changes

2024-06-11 15:03 UTC, olexandr-konovalov commented on glossary.yml
> +      користувача в SSH. Кожен SSH-ключ має окремі публічну та приватну частини; публічну
@Dod900ls1 you can add hyperlink to `[SSH](#ssh)` like in English text

2024-06-12 17:30 UTC, olexandr-konovalov approved these changes
@elletjies please merge this too! thanks!

2024-06-12 19:46 UTC, merged