Translate OOP to Ukrainian
carpentries/glosario pull request #670
Opened 2024-06-09 11:53 UTC by Herobread

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Oleksii Nazarenko

## Language: 

- Ukrainian

## Terms defined:

- OOP

2024-06-12 13:40 UTC, Dod900ls1 commented on glossary.yml
> +      [об'єкти](#object), які взаємодіють один з одним тільки через
"взяємодіють між собою" - коротше та як на мене звучить краще якщо читати вголос

2024-06-12 13:44 UTC, Dod900ls1 commented on glossary.yml
> +      Стиль програмування, в якому функції та дані зв'язуються разом в
Змінити "зв'язуються" на "Об'єднуются"?

2024-06-12 13:45 UTC, Dod900ls1 requested changes
Some suggestions.

2024-06-14 11:20 UTC, Dod900ls1 commented
Can you merge those 2 commits together using fixup command in rebase -i?

`git rebase -i HEAD~2`

you'll see smth like

```
pick 18a1f6df2295eba9444a78b8dbcae13a84f8d4ca Translate OOP to Ukrainian
pick abc123 update OOP in Ukrainian
```

you'll need to change it to 

```
pick 18a1f6df2295eba9444a78b8dbcae13a84f8d4ca Translate OOP to Ukrainian
fixup abc123 update OOP in Ukrainian
```
and exit rebase interface

2024-06-15 08:04 UTC, closed without merging

2024-06-15 08:11 UTC, Herobread commented
see #705

2024-06-15 08:45 UTC, olexandr-konovalov commented
Something went wrong - this got other commits from other places, I see ... There was a way to fix this without a new branch - next time, please get in touch, we can arrange a call and fix

2024-06-15 09:24 UTC, olexandr-konovalov commented
P.S. don't have time to investigate what went wrong, but to begin with, the instructions should have started with checking that you're on a right branch...

2024-06-15 09:25 UTC, Dod900ls1 commented
My bad

2024-06-15 16:00 UTC, Herobread commented
ok, will be careful next time