Translate "Boolean" to Ukrainian
carpentries/glosario pull request #672
Opened 2024-06-10 08:50 UTC by VeronikaShevc

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Veronika Shevchenko

## Language: 

- Ukrainian

## Terms defined:

- Boolean

2024-06-10 21:36 UTC, Herobread commented on glossary.yml
> +    term: "Булевий вираз"
"Булевий", наче повинно бути з маленької літери

в CONTRIBUTING.md нічого не сказано про велику/малу літеру, але наче зазвичай пишемо малу, якщо нема ніяких правил на велику літеру.

2024-06-10 21:59 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Булевий вираз"
Capitalisation of the 1st letter follows the rules of the language. For example, Glosario has man examples where nouns are capitalised in German, but not in other languages.

While in English it's "Boolean", in Ukrainian we say "булевий" without capitalisation, so I agree with @Herobread's suggestion.

`CONTRIBUTING.md` is ~3 years old, the most recent contributing guide is linked from the [README](https://github.com/carpentries/glosario/blob/main/README.md) file in its "Contributing" section.

2024-06-15 09:38 UTC, olexandr-konovalov commented on glossary.yml
> +      Він пов'язаний зі змінною або типом даних, які можуть мати логічне значення [істини](#true) або [хиби](#false).
Не починайте означення з "Він"

2024-06-15 09:41 UTC, olexandr-konovalov requested changes

2024-06-15 09:41 UTC, olexandr-konovalov commented on glossary.yml
> +      будуються на основі системи логічного обчислення між станами істини та хибності, 1 або 0.
Англійську пунктуацію не завжди доцільно просто копіювати. Мабуть краще  `(1 або 0)` у дужках?

2024-06-15 10:35 UTC, olexandr-konovalov commented on glossary.yml
> +      будуються на основі системи логічного обчислення між станами істини та хибності (1 або 0).
якщо пишемо тут "хибність", то мабуть двома рядками вище теж "істини або хибності" ?

2024-06-15 10:50 UTC, olexandr-konovalov commented
@sofiiamatios @Herobread @Dod900ls1 can at least one of you review this please

2024-06-15 10:50 UTC, olexandr-konovalov approved these changes

2024-06-15 16:23 UTC, Herobread approved these changes

2024-06-15 16:41 UTC, olexandr-konovalov approved these changes
@elletjies please merge

2024-06-15 17:49 UTC, merged