Translate "branch" to Ukrainian
carpentries/glosario pull request #675
Opened 2024-06-11 09:27 UTC by Herobread

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Oleksii Nazarenko

## Language: 

- Ukrainian

## Terms defined:

- branch
- git_branch

2024-06-12 13:52 UTC, Dod900ls1 commented on glossary.yml
> +      над окремими завданнями та уникати конфліктів з основною лінією.
"основною лінією розробки" в кінці

2024-06-12 13:54 UTC, Dod900ls1 requested changes
One small suggestion, but looks good for me in general

2024-06-12 15:41 UTC, Herobread commented on glossary.yml
> +      над окремими завданнями та уникати конфліктів з основною лінією.
Буде повторення з минулою лінією, тому, мабуть, залишу як є

2024-06-13 17:17 UTC, olexandr-konovalov commented on glossary.yml
> +      над окремими завданнями та уникати конфліктів з основною лінією.
"основною лінією проєкту" буде краще звучати, але щодо "лінії" маю сумніви. А як пояснюють гілки у https://git-scm.com/book/uk/v2 ?

2024-06-13 17:24 UTC, Herobread commented on glossary.yml
> +      над окремими завданнями та уникати конфліктів з основною лінією.
так, там в основному кажуть гілки, тому замінив і прибрав повторення

@Dod900ls1 @olexandr-konovalov

2024-06-13 17:24 UTC, Herobread commented
oops, autoformatted file, I will revert changes

2024-06-13 17:26 UTC, closed without merging

2024-06-13 17:34 UTC, Herobread commented
I have no idea what happened, I will just open new PR

2024-06-13 17:54 UTC, olexandr-konovalov commented
Good practice to cross-reference - e.g. superseded by #703. We might  have tried to reopen closed PR - it's possible, but if it's already done in #703, fine.