Translate "Byte" to Ukrainian
carpentries/glosario pull request #676
Opened 2024-06-11 11:26 UTC by VeronikaShevc

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Veronika Shevchenko

## Language: 

- Ukrainian

## Terms defined:

- Byte

2024-06-11 12:24 UTC, olexandr-konovalov commented on glossary.yml
> +      Це одиниця цифрової інформації, яка зазвичай складається з восьми [двійкових](#binary) цифр або [бітів](#bit).
Кома потрібна - без неї це має інше значення

2024-06-11 13:04 UTC, VeronikaShevc commented on glossary.yml
> +      Це одиниця цифрової інформації, яка зазвичай складається з восьми [двійкових](#binary) цифр або [бітів](#bit).
А де кому треба поставити?

2024-06-11 20:32 UTC, olexandr-konovalov commented on glossary.yml
> +      Це одиниця цифрової інформації, яка зазвичай складається з восьми [двійкових](#binary) цифр або [бітів](#bit).
Перед "або" - дивіться англійський текст

2024-06-18 22:43 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Байт"
please start with the lowercase letter

2024-06-18 22:44 UTC, olexandr-konovalov commented on glossary.yml
> +      Це одиниця цифрової інформації, яка зазвичай складається з восьми [двійкових](#binary) цифр, або [бітів](#bit).
"Це" не обовʼязково писатти (порівняйте з іншими термінами)

2024-06-20 22:00 UTC, olexandr-konovalov requested changes
@VeronikaShevc please respond to the latest suggestions

2024-06-26 07:16 UTC, olexandr-konovalov commented
@VeronikaShevc ping?

2024-06-27 13:00 UTC, Herobread approved these changes

2024-06-27 13:03 UTC, merged