Translate "Breadcrumbs" to Ukrainian
carpentries/glosario pull request #677
Opened 2024-06-11 11:43 UTC by VeronikaShevc

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Veronika Shevchenko

## Language: 

- Ukrainian

## Terms defined:

- Breadcrumbs

2024-06-12 09:51 UTC, Herobread requested changes

2024-06-12 09:51 UTC, Herobread commented on glossary.yml
> +      верхній частині сторінки. Навігаці́йні стежки показують користувачам, де вони знаходяться відносно решті веб-сайту;
решті -> решти

2024-06-13 14:32 UTC, Herobread requested changes

2024-06-13 14:32 UTC, Herobread commented on glossary.yml
>      term: "Навігаці́йні стежки (хлібні крихти)"
`Навігаці́йні` - з маленької літери

2024-06-13 16:59 UTC, olexandr-konovalov commented on glossary.yml
>      term: "Навігаці́йні стежки (хлібні крихти)"
А чому там `і` написано із якимось символом зверху ?

2024-06-15 10:55 UTC, olexandr-konovalov reviewed
@Herobread @sofiiamatios @Dod900ls1 could some of you review this please

2024-06-15 16:25 UTC, Herobread requested changes

2024-06-15 16:25 UTC, Herobread commented on glossary.yml
>        верхній частині сторінки. Навігаці́йні стежки показують користувачам, де вони знаходяться відносно решти веб-сайту;
why is there ; at the end?

usually we just put dot(?)

2024-06-16 17:00 UTC, Herobread approved these changes

2024-06-18 22:45 UTC, olexandr-konovalov commented on glossary.yml
> +      Термін заснований на казці "Гензель і Гретель", в якій діти залишають за собою слід з хлібних крихт, щоб знайти дорогу додому.
Як щодо "термін походить від казки" ?

2024-06-19 21:02 UTC, olexandr-konovalov approved these changes
@elletjies please merge

2024-06-20 05:38 UTC, merged