Translate "Commit_message" to Ukrainian
carpentries/glosario pull request #679
Opened 2024-06-11 13:18 UTC by VeronikaShevc

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Veronika Shevchenko

## Language: 

- Ukrainian

## Terms defined:

- Commit_message

2024-06-11 20:48 UTC, olexandr-konovalov requested changes

2024-06-11 20:48 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Повідоилення коміту"
ПовідоМлення

2024-06-11 20:48 UTC, olexandr-konovalov commented on glossary.yml
> +      Коментар, доданий до [коміту](#commit), який пояснює, що було зроблено та чому.
Мені біль сподобається "який пояснює, які зміни було зроблено та чому", але Ваш варіант також підходить

2024-06-12 08:50 UTC, Herobread requested changes

2024-06-12 08:50 UTC, Herobread commented on glossary.yml
> +      Коментар, доданий до [коміту](#commit), який пояснює, що було зроблено та чому.
мені більше подобається варіант з "зміни"

краще звучить у контексті git

2024-06-12 17:25 UTC, olexandr-konovalov commented on glossary.yml
> +      Коментар, доданий до [коміту](#commit), який пояснює, що було зроблено та чому.
Саме так!

2024-06-13 14:31 UTC, Herobread requested changes

2024-06-13 14:31 UTC, Herobread commented on glossary.yml
> +    term: "Повідомлення коміту"
`Повідомлення` - з маленької

2024-06-13 17:05 UTC, olexandr-konovalov approved these changes
@elletjies this seems ready - please merge. There is a line added within a slug - @VeronikaShevc please don't do this in new PRs. @elletjies I think I will make some maintenance PR laters, to clean up things like this systematically.

2024-06-13 17:37 UTC, merged