Translate "Binary" to Ukrainian
carpentries/glosario pull request #684
Opened 2024-06-11 16:00 UTC by sofiiamatios

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Sofiia Matios

## Language: 

- Ukrainian

## Terms defined:

- binary

2024-06-11 18:05 UTC, Herobread requested changes

2024-06-11 18:05 UTC, Herobread commented on glossary.yml
> +      представлена як 0 або 1. У [Булевий вираз](#boolean)
_Булевий вираз_

- неправильна форма
- неправильна велика/мала літера

2024-06-11 18:05 UTC, Herobread commented on glossary.yml
> +      логіці представлена як [хибний](#false) (0) або [істинний](#true) (1). Комп'ютери побудовані на системах,
maybe, change

[хибний](#false) (0) або [істинний](#true)
->
[хиби](#false) (0) або [істини](#true)

for consistency with [Boolean](https://github.com/carpentries/glosario/pull/672/files)

2024-06-11 18:13 UTC, sofiiamatios commented on glossary.yml
> +      логіці представлена як [хибний](#false) (0) або [істинний](#true) (1). Комп'ютери побудовані на системах,
@Herobread мені здається краще залишити хибний або істиний, тому що в попередньому реченні ми пояснюємо, що система має один з двох Станів (чоловічий рід) - хибний або істинний. Що думаєте?

2024-06-11 18:32 UTC, Herobread approved these changes

2024-06-11 18:32 UTC, Herobread commented on glossary.yml
> +      логіці представлена як [хибний](#false) (0) або [істинний](#true) (1). Комп'ютери побудовані на системах,
ок

2024-06-18 22:57 UTC, olexandr-konovalov commented on glossary.yml
> +      Система, яка може мати один з двох можливих станів. У комп'ютерних науках часто
Чи можна змінити "У комп'ютерних науках" на "В інформатиці" ?

2024-06-18 22:59 UTC, olexandr-konovalov commented on glossary.yml
> +      логіці представлена як [хибний](#false) (0) або [істинний](#true) (1). Комп'ютери побудовані на системах,
"представлена як хибний або істинний" якось не звучить: чому означення а не іменник? В іншому місці пи писали "хибність або істина" - для послідовності можна тут також

2024-06-19 05:05 UTC, sofiiamatios commented on glossary.yml
> +      логіці представлена як [хибний](#false) (0) або [істинний](#true) (1). Комп'ютери побудовані на системах,
@olexandr-konovalov виправила

2024-06-19 07:01 UTC, olexandr-konovalov commented
Looks good to me now, but needs a rebase to resolve conflicts with `main`.

2024-06-19 16:23 UTC, olexandr-konovalov approved these changes
@elletjies please merge

2024-06-19 17:54 UTC, merged