Translate "Cache" to Ukrainian
carpentries/glosario pull request #685
Opened 2024-06-11 16:08 UTC by sofiiamatios

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Sofiia Matios

## Language: 

- Ukrainian

## Terms defined:

- cache

2024-06-11 18:00 UTC, Herobread requested changes

2024-06-11 18:00 UTC, Herobread commented on glossary.yml
> +      The Центральний процесор в комп'ютері використовує апаратний кеш для зберігання
**The** Центральний процесор?

2024-06-18 23:13 UTC, olexandr-konovalov requested changes

2024-06-18 23:13 UTC, olexandr-konovalov commented on glossary.yml
> +      трафіку та затримок. Визначення, коли щось у кеші є застарілим і повинно бути замінене, є однією з
замінене -> оновлене

2024-06-18 23:13 UTC, olexandr-konovalov commented on glossary.yml
> +      трафіку та затримок. Визначення, коли щось у кеші є застарілим і повинно бути замінене, є однією з
"Перевірка, чи містить кеш застарілі дані, які потрібно оновити ... " ?

2024-06-19 04:46 UTC, sofiiamatios commented on glossary.yml
> +      трафіку та затримок. Визначення, коли щось у кеші є застарілим і повинно бути замінене, є однією з
@olexandr-konovalov виправила

2024-06-19 06:50 UTC, olexandr-konovalov commented
@Herobread please review

2024-06-19 10:56 UTC, Herobread commented on glossary.yml
> +      Щось, що зберігає копії даних, щоб майбутні запити до них могли бути виконані швидше.
maybe

Щось, що зберігає копії даних, щоб майбутні запити до них могли бути виконані швидше.
->
**Механізм**, що зберігає копії даних, щоб майбутні запити до них могли бути виконані швидше.

2024-06-21 21:18 UTC, olexandr-konovalov commented on glossary.yml
> +      Щось, що зберігає копії даних, щоб майбутні запити до них могли бути виконані швидше.
Мабуть навіть "Програмний або апаратний механізм" ?

2024-06-26 07:25 UTC, olexandr-konovalov commented on glossary.yml
> +      Щось, що зберігає копії даних, щоб майбутні запити до них могли бути виконані швидше.
@sofiiamatios could you please update this following these suggestions?

2024-09-04 14:35 UTC, olexandr-konovalov commented
@Herobread @sofiiamatios @VeronikaShevc please provide at lease one review

2024-09-04 15:52 UTC, VeronikaShevc approved these changes

2024-09-04 15:52 UTC, VeronikaShevc commented on glossary.yml
> +      [двох важких проблем в інформатиці](#two_hard_problems).
"найскладніших проблем"?

2024-09-04 16:04 UTC, olexandr-konovalov commented on glossary.yml
> +      [двох важких проблем в інформатиці](#two_hard_problems).
сподобалось - оновив

2024-09-04 16:05 UTC, VeronikaShevc approved these changes

2024-09-04 16:06 UTC, olexandr-konovalov approved these changes

2024-09-04 16:08 UTC, merged