Translate "caching" to Ukrainian
carpentries/glosario pull request #686
Opened 2024-06-11 16:11 UTC by sofiiamatios

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Sofiia Matios

## Language: 

- Ukrainian

## Terms defined:

- caching

2024-06-11 20:13 UTC, olexandr-konovalov commented on glossary.yml
> +      Зберегти копію деяких даних у локальному [кеші](#cache),щоб прискорити майбутній доступ.
Якщо "кешування", то тоді "Зберігання ... " а не "Зберегти"

2024-06-12 08:45 UTC, Herobread requested changes

2024-06-14 09:27 UTC, sofiiamatios commented on glossary.yml
> +      Зберегти копію деяких даних у локальному [кеші](#cache),щоб прискорити майбутній доступ.
@olexandr-konovalov виправила

2024-06-14 10:11 UTC, Herobread approved these changes

2024-06-14 22:57 UTC, olexandr-konovalov approved these changes
@elletjies please merge

2024-06-14 23:28 UTC, merged