Translate "cli" to Ukrainian
carpentries/glosario pull request #687
Opened 2024-06-11 16:16 UTC by sofiiamatios

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Sofiia Matios

## Language: 

- Ukrainian

## Terms defined:

- cli

2024-06-11 17:54 UTC, Herobread commented on glossary.yml
> +      Користувацький інтерфейс, який повністю покладається на текст для команд та виводу, зазвичай працює в [shell](#shell).
мабуть, [працює](https://slovnyk.ua/index.php?swrd=%D0%BF%D1%80%D0%B0%D1%86%D1%8E%D1%94+) -> [виконується](https://slovnyk.ua/index.php?swrd=%D0%B2%D0%B8%D0%BA%D0%BE%D0%BD%D1%83%D1%94%D1%82%D1%8C%D1%81%D1%8F)

і _shell_, мабуть, означає консоль(?)

2024-06-11 18:00 UTC, olexandr-konovalov commented on glossary.yml
> +      Користувацький інтерфейс, який повністю покладається на текст для команд та виводу, зазвичай працює в [shell](#shell).
"Користувацький" -? Мабуть "Інтерфейс користувача" ?

У Software Carpentry ми розглядали різні варіанти перекладу shell (консоль, оболонка тощо) та зупинилися на "термінал"

2024-06-11 18:01 UTC, olexandr-konovalov commented on glossary.yml
> +      Користувацький інтерфейс, який повністю покладається на текст для команд та виводу, зазвичай працює в [shell](#shell).
Тоді 
    зазвичай працює у [терміналі](#shell)

та перевірте як термін shell виглядає зараз

2024-06-11 18:22 UTC, sofiiamatios commented on glossary.yml
> +      Користувацький інтерфейс, який повністю покладається на текст для команд та виводу, зазвичай працює в [shell](#shell).
@olexandr-konovalov скрізь по різному, але загалом наче використовують "командна оболонка (shell)". що робимо, як все таки "shell" перекладаємо?

2024-06-12 20:53 UTC, olexandr-konovalov commented on glossary.yml
> +      Користувацький інтерфейс, який повністю покладається на текст для команд та виводу, зазвичай працює в [shell](#shell).
Також див. #692

2024-06-26 07:27 UTC, olexandr-konovalov commented on glossary.yml
> +      Користувацький інтерфейс, який повністю покладається на текст для команд та виводу, зазвичай працює в [shell](#shell).
@VeronikaShevc оскільки Ви зараз працюєте з перекладом уроку UNIX shell - подивіться, будь ласка, а яка там термінологія використовується. Було б добре бути послідовними.

2024-06-26 13:13 UTC, VeronikaShevc commented on glossary.yml
> +      Користувацький інтерфейс, який повністю покладається на текст для команд та виводу, зазвичай працює в [shell](#shell).
Нажаль зараз не можу подивитись у Crowdin. Мене не пускає до розділу shell-novice. Це ж у shell-novice, так?

2024-07-13 22:21 UTC, olexandr-konovalov commented on glossary.yml
> +      Користувацький інтерфейс, який повністю покладається на текст для команд та виводу, зазвичай працює в [shell](#shell).
@VeronikaShevc have you managed to check how to use here the terminology consistent with the UNIX shell lesson?

2024-07-14 17:21 UTC, VeronikaShevc commented on glossary.yml
> +      Користувацький інтерфейс, який повністю покладається на текст для команд та виводу, зазвичай працює в [shell](#shell).
Подивилась. Там shell йде як "термінал"

2024-07-14 19:47 UTC, olexandr-konovalov commented on glossary.yml
> +      Користувацький інтерфейс, який повністю покладається на текст для команд та виводу, зазвичай працює в [shell](#shell).
Thanks, very helpful

2024-11-13 11:23 UTC, olexandr-konovalov commented
@sofiiamatios @Herobread @VeronikaShevc could at least one of you review this please

2024-11-22 14:25 UTC, olexandr-konovalov requested changes

2024-11-22 14:25 UTC, olexandr-konovalov commented on glossary.yml
> +      Інтерфейс користувача, який повністю покладається на текст для команд та виводу,
... на текст для введення команнд та виведення результатів їх виконання...

(дякую @ChubOlya)

2024-12-02 16:20 UTC, olexandr-konovalov commented on glossary.yml
> +      Інтерфейс користувача, який повністю покладається на текст для команд та виводу,
@ChubOlya updated - could you review it, please?

2025-02-28 14:42 UTC, olexandr-konovalov commented on glossary.yml
> +      зазвичай використовується у [командній оболонці](#shell).
TODO: New sentence is better

2025-03-05 14:43 UTC, olexandr-konovalov commented on glossary.yml
> +      зазвичай використовується у [командній оболонці](#shell).
@sofiiamatios @VeronikaShevc @ChubOlya - made a separate sentence. Please approve.

2025-04-27 16:23 UTC, ChubOlya approved these changes

2025-04-27 16:32 UTC, olexandr-konovalov approved these changes

2025-04-27 16:33 UTC, merged