Translate "comment" to Ukrainian
carpentries/glosario pull request #689
Opened 2024-06-11 16:22 UTC by sofiiamatios

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Sofiia Matios

## Language: 

- Ukrainian

## Terms defined:

- comment

2024-06-11 17:42 UTC, Herobread requested changes

2024-06-11 17:42 UTC, Herobread commented on glossary.yml
> +      Текст, написаний у скрипті, який не вважається кодом для виконання, а отже, описує що робить код.
change
а отже, описує що робить код.
-> 
а описує що цей код робить.

2024-06-11 21:00 UTC, olexandr-konovalov commented on glossary.yml
> +      Зазвичай це короткі примітки, часто починаються з `#` (у багатьох мовах програмування).
примітки, які часто починаються...

Але ж мені здається, що "Текст, написаний у скрипті," буде незрозуміло

2024-06-14 09:25 UTC, sofiiamatios commented on glossary.yml
> +      Зазвичай це короткі примітки, часто починаються з `#` (у багатьох мовах програмування).
@olexandr-konovalov виправила

2024-06-15 08:35 UTC, olexandr-konovalov commented on glossary.yml
> +      Зазвичай це короткі примітки, часто починаються з `#` (у багатьох мовах програмування).
> Але ж мені здається, що "Текст, написаний у скрипті," буде незрозуміло

А що таке "скрипт" ? Як  Чи буде читачу це зрозуміло?

2024-06-19 04:50 UTC, sofiiamatios commented on glossary.yml
> +      Зазвичай це короткі примітки, часто починаються з `#` (у багатьох мовах програмування).
@olexandr-konovalov чи є якесь визначення як ми загально перекладаємо "скрипт"? у літературі бачила, що іноді використовують "сценарій" (послідовність операцій, які користувач може виконувати на комп'ютері)

2024-06-26 07:29 UTC, olexandr-konovalov commented on glossary.yml
> +      Зазвичай це короткі примітки, часто починаються з `#` (у багатьох мовах програмування).
@sofiiamatios Як щодо "Текст, написаний у вихідному коді, який не вважається інструкціями для виконання," ?

2024-07-13 22:32 UTC, olexandr-konovalov commented on glossary.yml
> +      Зазвичай цей текст - короткі примітки, які часто починаються з `#` (у багатьох мовах програмування).
+1

2024-09-04 14:49 UTC, olexandr-konovalov commented
@sofiiamatios @VeronikaShevc @Herobread @YehorBoiar please provide at lease one review

2024-09-04 15:52 UTC, VeronikaShevc approved these changes

2024-09-04 15:52 UTC, VeronikaShevc commented on glossary.yml
> +      Зазвичай цей текст - короткі примітки, які часто починаються з символу `#` (у багатьох мовах програмування).
Замість "примітки" може "нотатки"?

2024-09-04 16:18 UTC, olexandr-konovalov commented on glossary.yml
> +      Зазвичай цей текст - короткі примітки, які часто починаються з символу `#` (у багатьох мовах програмування).
Точно! Оновив

2024-09-04 16:18 UTC, VeronikaShevc approved these changes

2024-09-04 16:19 UTC, olexandr-konovalov approved these changes

2024-09-04 16:20 UTC, merged