Translate "compile" to Ukrainian
carpentries/glosario pull request #691
Opened 2024-06-11 16:32 UTC by sofiiamatios

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Sofiia Matios

## Language: 

- Ukrainian

## Terms defined:

- compile

2024-06-11 17:31 UTC, Herobread approved these changes
можна поставити лінію 2996 разом з 2995, але так - все ок

2024-06-11 18:06 UTC, Herobread approved these changes
можна поставити лінію 2996 разом з 2995, але так - все ок

2024-06-11 21:03 UTC, olexandr-konovalov requested changes

2024-06-11 21:03 UTC, olexandr-konovalov commented on glossary.yml
> +      Перетворити текстовий код в іншу форму. Програми у [компільованих
"текстовий код" - мабуть, треба сказати "текст або програмний код" ?

2024-06-11 21:03 UTC, olexandr-konovalov commented on glossary.yml
> +      мовах](#compiled_language) перетворюються на машинні існтрукції для виконання комп'ютером, а
існтрукції - друкарська помилка

2024-06-14 09:19 UTC, sofiiamatios commented on glossary.yml
> +      мовах](#compiled_language) перетворюються на машинні існтрукції для виконання комп'ютером, а
@olexandr-konovalov виправила

2024-06-15 08:27 UTC, olexandr-konovalov commented on glossary.yml
> +      Перетворити текст або програмний код в іншу форму. Програми у [компільованих
якщо "компілювати", то "перетворювати" (а якщо "відкомпілювати" то "перетворити")

2024-06-15 08:29 UTC, olexandr-konovalov commented on glossary.yml
> +      [Markdown](#markdown) зазвичай перетворюється у [HTML](#html) для відображення.
Мабуть

а текст у а форматі [Markdown](#markdown) зазвичай перетворюється у [HTML](#html) для відображення на вебсторінках.

2024-06-18 23:18 UTC, olexandr-konovalov requested changes
@sofiiamatios please see my most recent comments

2024-06-19 04:55 UTC, sofiiamatios commented on glossary.yml
> +      [Markdown](#markdown) зазвичай перетворюється у [HTML](#html) для відображення.
@olexandr-konovalov виправила

2024-06-19 06:55 UTC, olexandr-konovalov requested changes

2024-06-19 06:55 UTC, olexandr-konovalov commented on glossary.yml
> +      Перетворити текст або програмний код в іншу форму. Програми у [компільованих
Marked as resolved but no changes made - please either make them or justify leaving it as is

2024-06-20 09:03 UTC, YehorBoiar requested changes

2024-06-20 09:03 UTC, YehorBoiar commented on glossary.yml
> +      форматі [Markdown](#markdown) зазвичай перетворюється у [HTML](#html) для відображення на вебсторінках.
веб-сторінках

2024-06-20 09:07 UTC, olexandr-konovalov commented on glossary.yml
> +      форматі [Markdown](#markdown) зазвичай перетворюється у [HTML](#html) для відображення на вебсторінках.
No, "вебсторінках" is correct: https://www.uaredactor.com.ua/https-www-uaredactor-com-ua-zminy-v-novoy-redacciipravopysi/

2024-06-26 07:37 UTC, olexandr-konovalov commented on glossary.yml
> +      Перетворити текст або програмний код в іншу форму. Програми у [компільованих
@sofiiamatios please change Перетворити -> Перетворювати and it will be ready

2024-07-13 22:22 UTC, olexandr-konovalov commented on glossary.yml
> +      Перетворити текст або програмний код в іншу форму. Програми у [компільованих
pinging @sofiiamatios - this still waits, but should be easy - just one word to be changed

2024-09-04 14:41 UTC, olexandr-konovalov commented
@YehorBoiar @Herobread @VeronikaShevc @sofiiamatios please provide at least one review

2024-09-04 15:38 UTC, VeronikaShevc approved these changes

2024-09-04 15:40 UTC, olexandr-konovalov approved these changes

2024-09-04 15:41 UTC, merged