Translate "console" to Ukrainian
carpentries/glosario pull request #692
Opened 2024-06-11 16:35 UTC by sofiiamatios

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Sofiia Matios

## Language: 

- Ukrainian

## Terms defined:

- console

2024-06-11 17:25 UTC, Herobread commented on glossary.yml
> +      яка симулює такий пристрій.
або програма, така як shell, яка симулює такий пристрій.
->
або програма, наприклад оболонка, яка імітує такий пристрій.

2024-06-11 18:01 UTC, sofiiamatios commented on glossary.yml
> +      яка симулює такий пристрій.
@Herobread @olexandr-konovalov ми перекладаємо shell на оболонку?

2024-06-12 20:52 UTC, olexandr-konovalov commented on glossary.yml
> +      яка симулює такий пристрій.
Треба подумати та увʼязати із #687

2024-06-23 08:53 UTC, YehorBoiar requested changes
One suggestion

2024-06-23 08:53 UTC, YehorBoiar commented on glossary.yml
> +      Комп'ютерний термінал, де користувач може вводити команди, або програма, така як shell,
"або програмне забезпечення, таке як shell, яке імітує такий пристрій"?

2024-06-23 08:54 UTC, YehorBoiar commented on glossary.yml
> +      Комп'ютерний термінал, де користувач може вводити команди, або програма, така як shell,
Also, your PR has conflicts with the main branch. You need to `git rebase https://github.com/carpentries/glosario.git main` to resolve it.

2024-11-13 11:02 UTC, olexandr-konovalov commented
@sofiiamatios @YehorBoiar @Herobread @VeronikaShevc could at least one of you review this please

2024-11-22 14:29 UTC, ChubOlya requested changes

2024-11-22 14:29 UTC, ChubOlya commented on glossary.yml
> +      оболонка командного рядка, яка імітує такий пристрій.
Комп'ютерний термінал, де користувач може вводити команди, або програма, яка імітує такий пристрій, наприклад, оболонка командного рядка.

2024-12-02 16:15 UTC, olexandr-konovalov commented on glossary.yml
> +      оболонка командного рядка, яка імітує такий пристрій.
@ChubOlya fixed - please review!

2025-02-10 19:09 UTC, olexandr-konovalov commented on glossary.yml
> +      оболонка командного рядка, яка імітує такий пристрій.
@ChubOlya ping?

2025-02-28 14:47 UTC, olexandr-konovalov commented on glossary.yml
> +      яка імітує такий пристрій, наприклад, оболонка командного рядка.
Сказати треба "командна оболонка" (див #687)

2025-03-05 14:47 UTC, olexandr-konovalov commented on glossary.yml
> +      яка імітує такий пристрій, наприклад, оболонка командного рядка.
Done - now terminology agrees with #687 and also has a hyperlink. @VeronikaShevc @sofiiamatios @ChubOlya please review.

2025-04-27 16:30 UTC, olexandr-konovalov commented
@elletjies could you please merge this? Thanks!

2025-04-27 16:30 UTC, olexandr-konovalov approved these changes

2025-04-27 16:30 UTC, merged

2025-04-27 16:31 UTC, olexandr-konovalov commented
@elletjies false alarm - I've figured out that it waited for my own approval to allow me to merge :)