Translate "cran" to Ukrainian
carpentries/glosario pull request #694
Opened 2024-06-11 16:42 UTC by sofiiamatios

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Sofiia Matios

## Language: 

- Ukrainian

## Terms defined:

- cran

2024-06-11 16:52 UTC, olexandr-konovalov requested changes

2024-06-11 16:52 UTC, olexandr-konovalov commented on glossary.yml
> +      Публічний репозиторій [R](#r_language) пакетів.
R пакетів -> пакетів R

2024-06-11 16:52 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Комплексна мережа архіву R"
Comprehensive тут у сенсі всебічна, всеосяжна - але можу погодитись із "комплексна". Але ось "архіву R" не зовсім передає зміст

2024-06-11 17:56 UTC, sofiiamatios commented on glossary.yml
> +    term: "Комплексна мережа архіву R"
@olexandr-konovalov зрозуміла. шукала переклад в укр джерелах, все що знайшла - використовують або абревіатуру cran, або R(мова програмування). як порадите виправити?

2024-06-12 20:51 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Комплексна мережа архіву R"
@sofiiamatios Подивіться на https://cran.r-project.org/doc/FAQ/R-FAQ.html#What-is-CRAN_003f - буде зрозуміло, чому така назва, може це підкаже ідеї...

2024-06-26 07:40 UTC, olexandr-konovalov commented on glossary.yml
> +      Публічний репозиторій [R](#r_language) пакетів.
@sofiiamatios why did you mark this as resolved, but no changes were made - perhaps accidentally?

2024-06-26 07:42 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Комплексна мережа архіву R"
Я б залишив тоді term взагалі без перекладу

2024-07-13 22:25 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Комплексна мережа архіву R"
P.S. In which case I would extend the definition by explaining what CRAN stands for.

2025-05-07 15:57 UTC, vvkharchenko approved these changes

2025-05-07 15:58 UTC, olexandr-konovalov commented
@elletjies and please merge this one too ! thanks!

2025-05-07 16:01 UTC, elletjies commented
@all-contributors please add @sofiiamatios for translation

2025-05-07 16:02 UTC, merged