Translate "csv" to Ukrainian
carpentries/glosario pull request #695
Opened 2024-06-11 16:50 UTC by sofiiamatios

## Author: 

- Sofiia Matios

## Language: 

- Ukrainian

## Terms defined:

- csv

2024-06-11 17:15 UTC, Herobread requested changes

2024-06-11 17:15 UTC, Herobread commented on glossary.yml
> +      [строкових значень](#string).
строкових значень -> рядків

(ми так вже переклали string)

2024-06-11 17:15 UTC, Herobread commented on glossary.yml
> +      [строкових значень](#string).
і оригінал мав на увазі на просто використання рядків, а різні лапки наволо них

" і '

2024-06-11 17:50 UTC, sofiiamatios commented on glossary.yml
> +      [строкових значень](#string).
> і оригінал мав на увазі на просто використання рядків, а різні лапки наволо них
> 
> " і '

@Herobread що саме ви тут маєте на увазі? 
string зміню зараз, дякую!

2024-06-11 17:53 UTC, sofiiamatios commented on glossary.yml
@olexandr-konovalov got it!

2024-06-11 18:21 UTC, Herobread commented on glossary.yml
> +      [строкових значень](#string).
English:

> There are many minor variations, particularly around **quoting** of [strings](#string).

тобто, просто додай частину про використання лапок наволо рядків

2024-06-11 18:28 UTC, Herobread approved these changes

2024-06-12 21:00 UTC, olexandr-konovalov commented on glossary.yml
> +      Текстовий формат для табличних даних, в якому кожен [запис](#record) - один рядок, а [значення](#field)
Маю сумніви щодо "значення" (value). Мабуть "поля"?

2024-06-12 21:00 UTC, olexandr-konovalov commented on glossary.yml
> +      розділені комами. Існує багато незначних варіацій, особливо щодо використання лапок навокло
Мабуть "Має багато незначних..." ?

2024-06-13 21:06 UTC, olexandr-konovalov commented on glossary.yml
> +      розділені комами. Існує багато незначних варіацій, особливо щодо використання лапок навокло
навокло -> навколо

2024-06-14 09:13 UTC, sofiiamatios commented on glossary.yml
> +      розділені комами. Існує багато незначних варіацій, особливо щодо використання лапок навокло
@olexandr-konovalov все виправила

2024-06-14 23:04 UTC, olexandr-konovalov approved these changes
@elletjies please merge

2024-06-14 23:28 UTC, merged