Translate "debug" to Ukrainian
carpentries/glosario pull request #696
Opened 2024-06-11 16:54 UTC by sofiiamatios

## Author: 

- Sofiia Matios

## Language: 

- Ukrainian

## Terms defined:

- debug

2024-06-11 17:05 UTC, olexandr-konovalov requested changes

2024-06-11 17:05 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "дебаг"
Це дуже жаргонний вираз. Треба подивитись приклади у літературі. Або писати 

"пошук і виправлення помилок (debugging)"

2024-06-11 17:09 UTC, Herobread commented on glossary.yml
> +    term: "дебаг"
мабуть, більш коректний переклад буде **налагодження**

дебаг - дуже популярний варіант, але це більше як сленг

2024-06-11 17:52 UTC, olexandr-konovalov commented on glossary.yml
> +      В комп'ютерному середовищі 'налагодження' відноситься до процесу пошуку та виправлення помилок (також відомих як 'баги') в комп'ютерних програмах або системах.
Чи в українській мові лапки завжди подвійні?

2024-06-11 18:24 UTC, Herobread commented on glossary.yml
> +      В комп'ютерному середовищі 'налагодження' відноситься до процесу пошуку та виправлення помилок (також відомих як 'баги') в комп'ютерних програмах або системах.
дуже рідко:

‘одинарні лапки’ — застосовуються для описів значень слів і в перекладах іншомовних слів (наприклад: слово «шумовка» запозичене від польського дієслова szumować , тобто ‘знімати піну’ від szum ‘піна’ ). Зустрічаються вони настільки рідко, що пам’ятаю, що десь таке бачила, а от навести гарний приклад, то і не змогла знайти потрібний текст. 

[source](https://www.profi-text.rv.ua/4-vydy-lapok-shcho-de-dorechno-i-shcho-de-pravylno-zastosovuvaty/)

2024-06-14 10:07 UTC, Herobread approved these changes

2024-06-23 08:39 UTC, YehorBoiar approved these changes
LGTM!

2024-06-26 07:45 UTC, olexandr-konovalov commented
I am waiting till we conclude our discussion in #699

2024-07-13 22:48 UTC, olexandr-konovalov requested changes

2024-07-13 22:48 UTC, olexandr-konovalov commented on glossary.yml
> +      В комп'ютерному середовищі "налагодження" відноситься до процесу пошуку та виправлення помилок (також відомих як "баги") в комп'ютерних програмах або системах.
Я б сказав "(також відомих як дефекти, або, неформально, "баги")" та ще б додав лінк до означення терміну  "дефект" у #699

2024-09-04 15:28 UTC, olexandr-konovalov commented
@sofiiamatios @Herobread @VeronikaShevc @YehorBoiar please provide at lease one review

2024-09-04 15:30 UTC, VeronikaShevc approved these changes

2024-09-04 15:32 UTC, olexandr-konovalov approved these changes

2024-09-04 15:33 UTC, merged

2025-03-31 08:23 UTC, elletjies commented
@all-contributors please add @sofiiamatios for translation