Translate "browser_cache" to Ukrainian
carpentries/glosario pull request #704
Opened 2024-06-14 10:32 UTC by Herobread

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Oleksii Nazarenko

## Language: 

- Ukrainian

## Terms defined:

- browser cache

2024-06-18 08:41 UTC, YehorBoiar commented on glossary.yml
> +      Місце, де веб-браузери зберігають копії раніше отриманих файлів (веб-сторінок, файлів даних)
"раніше отриманих файлів"
"раніше завантажених файлів"

2024-06-18 08:43 UTC, YehorBoiar requested changes
Some changes required

2024-06-18 08:43 UTC, YehorBoiar commented on glossary.yml
> +      Місце, де веб-браузери зберігають копії раніше отриманих файлів (веб-сторінок, файлів даних)
"раніше отриманих файлів" -> "раніше завантажених файлів"

2024-06-18 08:43 UTC, YehorBoiar commented on glossary.yml
> +      щоб заощадити час при повторному запиті. Іноді можуть виникати проблеми, якщо в Інтернеті є
"щоб заощадити час при повторному запиті" -> "для економії часу при повторному запиті"

2024-06-18 08:43 UTC, YehorBoiar commented on glossary.yml
> +      новіша версія, але браузер її не помічає.
"але браузер її не помічає" -> "але браузер її не завантажує"

2024-06-20 08:35 UTC, Herobread commented
@YehorBoiar agreed with all, please review

2024-06-20 08:48 UTC, YehorBoiar requested changes

2024-06-20 08:48 UTC, YehorBoiar commented on glossary.yml
> +      новіша версія, але браузер її не завантажує.
новіша версія файлу?

2024-06-20 14:34 UTC, Herobread commented on glossary.yml
> +      новіша версія, але браузер її не завантажує.
@YehorBoiar changed to `більш актуальна`

2024-06-21 21:24 UTC, olexandr-konovalov commented on glossary.yml
> +      новіша версія, але браузер її не завантажує.
Мабуть "свіжа" ?

2024-06-23 08:34 UTC, YehorBoiar requested changes

2024-06-23 08:34 UTC, YehorBoiar commented on glossary.yml
> +      більш актуальна версія, але браузер її не завантажує.
"більш актуальна версія файлу"?

2024-06-23 16:25 UTC, Herobread commented on glossary.yml
> +      більш актуальна версія, але браузер її не завантажує.
@YehorBoiar updated

2024-06-23 17:30 UTC, YehorBoiar approved these changes

2024-06-23 17:31 UTC, olexandr-konovalov commented on glossary.yml
> +      новіша версія, але браузер її не завантажує.
@YehorBoiar @Herobread всеж-таки якось дивно чути "актуальна" у такому контексті - порівняйте з https://sum20ua.com/?wordid=753&page=32&searchWord=%D0%B0%D0%BA%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0#lid_753

2024-06-28 10:11 UTC, YehorBoiar commented
LGTM! @olexandr-konovalov

2024-06-28 22:26 UTC, olexandr-konovalov approved these changes

2024-07-13 22:09 UTC, olexandr-konovalov commented on glossary.yml
> +      новіша версія, але браузер її не завантажує.
@Herobread @YehorBoiar все ще маю сумніви щодо "актуальна" - див. вище

2024-07-14 18:37 UTC, Herobread commented
@olexandr-konovalov please merge

2024-07-14 19:40 UTC, olexandr-konovalov commented
@Herobread please see above - все ще маю сумніви щодо "актуальна": https://sum20ua.com/?wordid=753&page=32&searchWord=%D0%B0%D0%BA%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0#lid_753 

Are you sure it's OK? Any examples?

2024-07-14 21:07 UTC, Herobread commented
@olexandr-konovalov I agree, `актуальна` is a bit off, so I have changed to `нова`

2024-07-14 22:30 UTC, olexandr-konovalov approved these changes

2024-07-14 22:30 UTC, merged