Translate "filesystem" to Ukrainian
carpentries/glosario pull request #709
Opened 2024-06-15 16:56 UTC by Herobread

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Oleksii Nazarenko

## Language: 

- Oleksii

## Terms defined:

- filesystem

2024-06-18 23:40 UTC, olexandr-konovalov requested changes

2024-06-18 23:40 UTC, olexandr-konovalov commented on glossary.yml
> +      Частина [операційної системи](#operating_system), яка керує тим, як файли
"керує" тут не зовсім натурально звучить. Може "яка відповідає за" або "яка забезпечує" і далі змінити відповідно на "зберігання та доступ до файлів"

2024-06-18 23:40 UTC, olexandr-konovalov commented on glossary.yml
> +      зберігаються та отримуються. Також використовується для визначення способу
мені здається, що "визначення" тут не підходить. Мабуть "для посилання на конкретний спосіб їх зберігання"?

2024-06-20 08:24 UTC, Herobread commented on glossary.yml
> +      зберігаються та отримуються. Також використовується для визначення способу
@olexandr-konovalov updated, sounds better

2024-06-20 08:25 UTC, Herobread commented on glossary.yml
> +      Частина [операційної системи](#operating_system), яка керує тим, як файли
I tried those options and they all sound a bit too wordy, so I kept as it is

2024-06-20 14:31 UTC, Herobread commented on glossary.yml
> +      Частина [операційної системи](#operating_system), яка керує тим, як файли
I see now, `керує` is indeed out of place

I have updated

2024-06-20 14:46 UTC, olexandr-konovalov approved these changes
LGTM! Please ask someone else to review.

2024-06-20 14:49 UTC, olexandr-konovalov commented on glossary.yml
> +      Частина [операційної системи](#operating_system), яка керує тим, як файли
@Herobread  а як щодо "зберігання та доступ до файлів"  - тому що незрозуміло що таке "отримуються"

2024-06-21 21:28 UTC, olexandr-konovalov requested changes
як щодо "зберігання та доступ до файлів" - тому що незрозуміло що таке "отримуються". Ким отримуються ? "Отримуються" звучить нібито як ззовні отримуються.

Duplicating the comment to be able to request changes properly

2024-06-23 16:19 UTC, Herobread commented
@olexandr-konovalov sounds better now, I have updated

2024-06-23 17:27 UTC, olexandr-konovalov approved these changes
LGTM! Need 2nd reviewer - @VeronikaShevc or @sofiiamatios ?

2024-06-23 17:29 UTC, VeronikaShevc approved these changes

2024-06-23 17:32 UTC, olexandr-konovalov approved these changes
@elletjies please merge

2024-06-24 16:42 UTC, merged