Translate "big data" to Ukrainian
carpentries/glosario pull request #712
Opened 2024-06-18 08:12 UTC by YehorBoiar

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Yehor Boiar

## Language: 

- Ukrainian

## Terms defined:

- big data

2024-06-22 10:10 UTC, YehorBoiar commented
@Herobread @VeronikaShevc Please review

2024-06-22 11:45 UTC, VeronikaShevc requested changes

2024-06-22 11:45 UTC, VeronikaShevc commented on glossary.yml
> +    term: "big data"
Тут начебто "великі дані"?

2024-06-22 11:45 UTC, VeronikaShevc commented on glossary.yml
> +      Великі та складні набори даних з нових джерел, які занадто об'ємні для
Може "збірки даних"?

2024-06-22 12:12 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "big data"
"Big data" стало усталеним словосполученням в англійськйї мові. Якщо так то я б помістив його у дужках, тобто

великі дані (big data)

2024-06-23 08:28 UTC, YehorBoiar commented
@olexandr-konovalov @VeronikaShevc Agreed. Corrected. Please review.

2024-06-23 16:29 UTC, Herobread commented on glossary.yml
> +      Збірки даних з нових джерел, які занадто об'ємні для
why `нових джерел`, can they only come from new sources?

2024-06-24 07:27 UTC, YehorBoiar commented
@Herobread @VeronikaShevc Please review.

2024-06-24 08:08 UTC, Herobread approved these changes

2024-06-26 08:17 UTC, olexandr-konovalov commented on glossary.yml
> +      Збірки даних, які занадто об'ємні для ефективної обробки традиційним програмним забезпеченням.
Не зовсім впевнений. "Any data that until recently was too big for most people to work with on a single computer" робить акцент на обмеженнях з приводу оперативної памʼяті та зберігання даних, а не на "традиційності", яка є субʼєктивною оцінкою.

2024-06-26 09:36 UTC, YehorBoiar commented
@olexandr-konovalov @Herobread  Corrected. Please review.

2024-06-26 10:02 UTC, olexandr-konovalov approved these changes
LGTM now - waiting for others

2024-06-27 12:54 UTC, Herobread approved these changes

2024-06-27 12:59 UTC, merged