Translate "code coverage" to Ukrainian
carpentries/glosario pull request #714
Opened 2024-06-18 08:38 UTC by YehorBoiar

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Yehor Boiar

## Language: 

- Ukrainian

## Terms defined:

- code coverage

2024-06-18 23:45 UTC, olexandr-konovalov requested changes

2024-06-18 23:45 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "Покриття коду (в тестуванні)"
start with lowercase

2024-06-18 23:45 UTC, olexandr-konovalov commented on glossary.yml
> +      Наскількі велика частина бібліотеки або програми виконується під час запуску тестів.
"Показник, який ..." 

запуску -> виконання

2024-06-18 23:45 UTC, olexandr-konovalov commented on glossary.yml
> +      Зазвичай виражається у відсотках від рядків коду: наприклад, якщо під час тестування
від кількості рядків (?)

2024-06-18 23:45 UTC, olexandr-konovalov commented on glossary.yml
> +      виконується 40 з 50 рядків у файлі, то ці тести мають 80% покриття коду.
то код має 80% покриття тестами

2024-06-19 10:18 UTC, YehorBoiar commented
@olexandr-konovalov @VeronikaShevc please review

2024-06-19 16:28 UTC, olexandr-konovalov reviewed
LGTM, thanks! @VeronikaShevc what do you think?

2024-06-20 08:19 UTC, Herobread approved these changes

2024-06-20 10:33 UTC, olexandr-konovalov approved these changes
Thanks for the 2nd review @Herobread. @elletjies please merge

2024-06-20 10:37 UTC, merged