Translate "Whitespace" to Ukrainian
carpentries/glosario pull request #715
Opened 2024-06-18 20:21 UTC by VeronikaShevc

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Veronika Shevchenko

## Language: 

- Ukrainian

## Terms defined:

- Whitespace

2024-06-18 22:32 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "cимвол нового рядка"
Це не тільки символ нового рядка, а ще й пробіл, табуляція тощо - треба шукати інший переклад

2024-06-26 08:22 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "cимвол нового рядка"
@VeronikaShevc Див. https://uk.wikipedia.org/wiki/%D0%9D%D0%B5%D0%B4%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%B0%D0%BD%D1%96_%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%B8_%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%B2%D0%B8%D1%85_%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%BE%D1%80%D1%96%D0%B2

2024-06-26 13:00 UTC, VeronikaShevc commented on glossary.yml
> +    term: "cимвол нового рядка"
Виправити на "Недруковані символи" або на це "Недруковані символи текстових процесорів"?

Що краще?

2024-06-26 17:04 UTC, olexandr-konovalov commented on glossary.yml
> +    term: "cимвол нового рядка"
"Недруковані символи" як термін, з перекладом починаючи з "У текстових процесорах - символи, які займають місце, але не створюють видимої позначки, такі як пробіл..."

2024-06-26 19:38 UTC, olexandr-konovalov requested changes

2024-06-26 19:38 UTC, olexandr-konovalov commented on glossary.yml
> +      або горизонтальна чи вертикальна табуляція. Назва походить від їх появи на друкованій сторінці в епоху друкарських машинок.
"Назва походить від їх появи на друкованій сторінці в епоху друкарських машинок." має сенс як пояснення у англійській мові, а у перекладі пропоную видалити повністю це речення.

2024-06-30 22:57 UTC, olexandr-konovalov approved these changes
LGTM! @sofiiamatios @Herobread @YehorBoiar could one or more of you review this please

2024-07-01 08:43 UTC, YehorBoiar approved these changes

2024-07-01 08:43 UTC, YehorBoiar commented on glossary.yml
> +      такі як пробіл, новий рядок, розрив рядка або горизонтальна чи вертикальна табуляція.
LGTM!

2024-07-01 23:03 UTC, merged