Translate "source_code" to Ukrainian
carpentries/glosario pull request #716
Opened 2024-06-18 21:01 UTC by VeronikaShevc

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Veronika Shevchenko

## Language: 

- Ukrainian

## Terms defined:

- source_code

2024-06-19 05:09 UTC, sofiiamatios reviewed
простіше кажучи -> просто. 

Це в основному створена людиною серія -> В основному це створена людиною серія

2024-06-19 07:12 UTC, olexandr-konovalov commented on glossary.yml
> +
this is tolerable, but no need to add an extra blank line

2024-06-19 20:05 UTC, olexandr-konovalov commented on glossary.yml
> +      складається програма. (Примітка: для деяких додатків існують автоматичні генератори коду)
додатків -> застосунків

2024-06-19 20:06 UTC, olexandr-konovalov commented on glossary.yml
> +
Noticed this addressed, thanks - but what with @sofiiamatios' comment above?

2024-06-19 20:33 UTC, olexandr-konovalov commented
@YehorBoiar @Herobread could one or both of you review please

2024-06-20 08:16 UTC, Herobread requested changes

2024-06-20 08:16 UTC, Herobread commented on glossary.yml
> +      інтерпретатора, або компілятора). В основному це створена людиною серія команд, з яких
В основному, <- add coma, I think

2024-06-20 14:23 UTC, Herobread approved these changes

2024-06-21 21:35 UTC, olexandr-konovalov commented on glossary.yml
> +      Вихідний код або, просто, код, який є джерелом виконаного коду (або за допомогою
Пунктуація трохи змінила зміст. Мається на увазі що вихідний код можна також просто назвати "код" - а поточний переклад виглядкає ніби віхідний код - це "код, який ..."  - важко читати

2024-06-22 13:58 UTC, VeronikaShevc commented on glossary.yml
> +      Вихідний код або, просто, код, який є джерелом виконаного коду (або за допомогою
Вихідний код або первинний код - це джерело коду (цей код було виконано за допомогою інтерпретатора або компілятора). Здебільшого, це створена людиною серія команд, з яких складається програма. (Примітка: для деяких застосунків існують автоматичні генератори коду)

Може щось накшталт цього?

2024-06-22 14:30 UTC, olexandr-konovalov commented on glossary.yml
> +      Вихідний код або, просто, код, який є джерелом виконаного коду (або за допомогою
Тоді "Вихідний код, або первинний код - це джерело коду, який виконується за допомогою інтерпретатора або компілятора." - а далі як в Вас написано. Кома перед "або", тому що дві назви того ж самого

2024-06-22 17:36 UTC, olexandr-konovalov reviewed
LGTM! @elletjies merge please!

@elletjies what do you do with PRs having many commits - are you using "squash and merge" strategy?

2024-06-24 16:41 UTC, elletjies approved these changes

2024-06-24 16:41 UTC, merged