Translate "test data" to Ukrainian
carpentries/glosario pull request #719
Opened 2024-06-19 11:18 UTC by Herobread

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Oleksii Nazarenko

## Language: 

- Ukrainian

## Terms defined:

- test_data

2024-06-28 10:22 UTC, YehorBoiar commented on glossary.yml
> +      щоб гарантувати, що модель належним чином протестована з небаченими даними.
"щоб щоб" -> "щоб"

2024-06-28 20:39 UTC, Herobread commented on glossary.yml
> +      щоб гарантувати, що модель належним чином протестована з небаченими даними.
@YehorBoiar updated

2024-06-29 09:45 UTC, YehorBoiar requested changes

2024-06-29 09:45 UTC, YehorBoiar commented on glossary.yml
> +      Тестові дані - це фрагмент набору даних, який використовується для оцінки коректності
"Тестові дані -" -> ""

2024-06-29 09:45 UTC, YehorBoiar commented on glossary.yml
> +      гарантувати, що модель належним чином протестована з небаченими даними.
"що модель належним чином протестована з небаченими даними." -> "що модель належним чином протестована на раніше не використаних даних."

2024-06-29 18:38 UTC, Herobread commented
@YehorBoiar updated, please review

2024-06-29 23:01 UTC, olexandr-konovalov commented on glossary.yml
> +      Вони завжди повинні бути відокремлені від [тренувальних даних](#training_data), щоб
Вони  -> тестові дані, інакше вони - фрагмент (?)

2024-06-29 23:03 UTC, olexandr-konovalov commented on glossary.yml
> +      гарантувати, що модель належним чином протестована на раніше не використаних даних.
Мабуть "на даних, які не використовувались раніше" ?

2024-07-03 19:55 UTC, Herobread commented
@olexandr-konovalov @YehorBoiar updated, please review

2024-07-03 22:29 UTC, olexandr-konovalov approved these changes

2024-07-04 09:21 UTC, YehorBoiar requested changes

2024-07-04 09:21 UTC, YehorBoiar commented on glossary.yml
> +      гарантувати, що модель належним чином протестована на даних, які не використовувались раніше.
використовувались -> використовувалися

2024-07-04 09:21 UTC, YehorBoiar commented on glossary.yml
> +      фрагмент набору даних, який використовується для оцінки коректності
Фрагмент - upper case. 
Фрагмент or Частина? Not sure which one is better.

2024-07-04 17:35 UTC, Herobread commented
@olexandr-konovalov @YehorBoiar updated, please review

2024-07-04 20:06 UTC, olexandr-konovalov commented on glossary.yml
> +      фрагмент набору даних, який використовується для оцінки коректності
+1 for "Частина"

2024-07-12 19:45 UTC, olexandr-konovalov approved these changes

2024-07-12 19:47 UTC, olexandr-konovalov commented on glossary.yml
> +      фрагмент набору даних, який використовується для оцінки коректності
> Фрагмент or Частина? Not sure which one is better.

@Herobread what do you think?

2024-07-13 07:52 UTC, Herobread commented
@olexandr-konovalov @YehorBoiar changed `фрагмент` to `частина`

2024-07-13 07:54 UTC, YehorBoiar approved these changes

2024-07-13 11:05 UTC, merged