translate 'training data' to Ukrainian
carpentries/glosario pull request #720
Opened 2024-06-19 11:24 UTC by Herobread

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Oleksii Nazarenko

## Language: 

- Ukrainian

## Terms defined:

- training data

2024-06-28 10:30 UTC, YehorBoiar requested changes

2024-06-28 10:30 UTC, YehorBoiar commented on glossary.yml
> +      Тренувальні дані - це фрагмент набору даних, який використовується для тренування алгоритму
"Тренувальні дані - це" - unnecessary

2024-06-28 10:30 UTC, YehorBoiar commented on glossary.yml
> +      [машинного навчання](#machine_learning) щоб розпізнувати схожі данні. Вони завжди мають бути відокремлені від
данні -> дані

2024-06-28 10:30 UTC, YehorBoiar commented on glossary.yml
> +      ніколи не бачила.
"ніколи не бачила" -> "раніше не використовуваних даних"

2024-06-28 20:36 UTC, Herobread commented on glossary.yml
> +      Тренувальні дані - це фрагмент набору даних, який використовується для тренування алгоритму
same issue in English version

2024-06-28 20:38 UTC, Herobread commented
@YehorBoiar updated, please review

2024-06-29 09:42 UTC, YehorBoiar commented on glossary.yml
> +      [тестових даних](#test_data), щоб гарантувати, що модель належним чином протестована на, раніше не використаних, даних.
"що модель належним чином протестована на," -> "що модель належним чином протестована на даних,"

2024-06-29 18:35 UTC, Herobread commented on glossary.yml
> +      [тестових даних](#test_data), щоб гарантувати, що модель належним чином протестована на, раніше не використаних, даних.
very similar, so I will leave it as it is

2024-06-29 23:05 UTC, olexandr-konovalov commented on glossary.yml
> +      [машинного навчання](#machine_learning) щоб розпізнувати схожі дані. Вони завжди мають бути відокремлені від
Хто "вони" - краще "тренувальні дані"

2024-06-29 23:05 UTC, olexandr-konovalov commented on glossary.yml
> +      [тестових даних](#test_data), щоб гарантувати, що модель належним чином протестована на, раніше не використаних, даних.
протестована на даних, які не використовувались раніше?

2024-07-03 19:53 UTC, Herobread commented on glossary.yml
> +      [тестових даних](#test_data), щоб гарантувати, що модель належним чином протестована на, раніше не використаних, даних.
sure

2024-07-03 19:53 UTC, Herobread commented
@olexandr-konovalov @YehorBoiar updated, please review

2024-07-03 22:38 UTC, olexandr-konovalov commented on glossary.yml
> +      [машинного навчання](#machine_learning) щоб розпізнувати схожі дані.
У цьому рядку треба перевірити - чи кома перед "щоб", чи ще слова додати

2024-07-04 09:30 UTC, YehorBoiar requested changes

2024-07-04 09:30 UTC, YehorBoiar commented on glossary.yml
> +      фрагмент набору даних, який використовується для тренування алгоритму
Starts with upper case

2024-07-04 09:30 UTC, YehorBoiar commented on glossary.yml
> +      щоб гарантувати, що модель протестована на даних, які не використовувались раніше.
використовувалися

2024-07-04 17:49 UTC, Herobread commented
@olexandr-konovalov @YehorBoiar updated, please review

2024-07-04 20:04 UTC, olexandr-konovalov approved these changes

2024-07-05 07:14 UTC, YehorBoiar approved these changes

2024-07-09 13:47 UTC, Herobread commented
@olexandr-konovalov please remove the do not merge label

2024-07-12 19:49 UTC, olexandr-konovalov commented
@Herobread до речі, фрагмент чи частина? Див. #719

2024-07-13 07:54 UTC, Herobread commented
@olexandr-konovalov @YehorBoiar changed `фрагмент` to `частина`

2024-07-13 11:06 UTC, merged