Translate markdown to Ukrainian
carpentries/glosario pull request #730
Opened 2024-06-26 08:57 UTC by Herobread

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Oleksii Nazarenko

## Language: 

- Ukrainian

## Terms defined:

- Markdown

2024-06-28 10:36 UTC, YehorBoiar requested changes

2024-06-28 10:36 UTC, YehorBoiar commented on glossary.yml
> +      [Мова розмітки](#markup_language) з простим синтаксисом, призначена для заміни [HTML](#html).
"призначена для заміни [HTML](#html)" -> "призначена для полегшення написання та читання коду в текстовому форматі. Вона також дозволяє легко конвертувати текст у  HTML"

2024-06-28 20:35 UTC, Herobread commented on glossary.yml
> +      [Мова розмітки](#markup_language) з простим синтаксисом, призначена для заміни [HTML](#html).
@YehorBoiar agreed, updated

2024-06-29 09:40 UTC, YehorBoiar requested changes

2024-06-29 09:40 UTC, YehorBoiar commented on glossary.yml
> +      читання коду в текстовому форматі. Вона також дозволяє легко конвертувати текст у [HTML](#html).
"призначена для полегшення написання та читання коду в текстовому форматі." -> "для полегшення написання та читання тексту в структурованому форматі."

2024-06-29 18:32 UTC, Herobread commented on glossary.yml
> +      читання коду в текстовому форматі. Вона також дозволяє легко конвертувати текст у [HTML](#html).
@YehorBoiar updated

2024-06-30 07:51 UTC, YehorBoiar requested changes

2024-06-30 07:51 UTC, YehorBoiar commented on glossary.yml
> +      тексту в структурованому форматі. Вона також дозволяє легко конвертувати текст у [HTML](#html).
"Вона також дозволяє легко конвертувати текст у [HTML](#html)." - should we refer to Markdown term using instead of "Мова розмітки"?

2024-06-30 07:51 UTC, YehorBoiar commented on glossary.yml
> +      [Мова розмітки](#markup_language) з простим синтаксисом, для полегшення написання та читання
Do we really need "з простим синтаксисом" in here? I don't see how it is contributing to definition.

2024-07-03 19:50 UTC, Herobread commented on glossary.yml
> +      тексту в структурованому форматі. Вона також дозволяє легко конвертувати текст у [HTML](#html).
sure

2024-07-03 19:50 UTC, Herobread commented on glossary.yml
> +      [Мова розмітки](#markup_language) з простим синтаксисом, для полегшення написання та читання
it's one of the main markdown features, so I will keep it

2024-07-03 22:34 UTC, olexandr-konovalov commented on glossary.yml
> +      [Мова розмітки](#markup_language) з простим синтаксисом, для полегшення написання та читання
Як щодо такого:

[Мова розмітки](#markup_language) для полегшення написання та читання тексту в структурованому форматі. Markdown також дозволяє легко конвертувати текст у [HTML](#html). Markdown має простий синтаксис, та часто використовується для файлів README, а також є основою для [R markdown](#r_markdown).

2024-07-04 09:26 UTC, YehorBoiar commented on glossary.yml
> +      [Мова розмітки](#markup_language) з простим синтаксисом, для полегшення написання та читання
LGTM!
"тексту в структурованому" -> "тексту у структурованому"

2024-07-04 09:26 UTC, YehorBoiar commented on glossary.yml
> +      тексту в структурованому форматі. Markdown також дозволяє легко конвертувати текст у [HTML](#html).
у структурованому

2024-07-04 17:45 UTC, Herobread commented
@YehorBoiar @olexandr-konovalov updated, please review

2024-07-04 20:05 UTC, olexandr-konovalov approved these changes

2024-07-05 07:15 UTC, YehorBoiar approved these changes

2024-07-09 13:48 UTC, Herobread commented
@olexandr-konovalov please merge

2024-07-12 19:50 UTC, merged