Translate "pandas" to Ukrainian
carpentries/glosario pull request #732
Opened 2024-06-30 20:42 UTC by VeronikaShevc

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Veronika Shevchenko

## Language: 

- Ukrainian

## Terms defined:

- pandas

2024-07-01 08:35 UTC, YehorBoiar requested changes

2024-07-01 08:35 UTC, YehorBoiar commented on glossary.yml
> +      pandas - це пакет Python з відкритим вихідним кодом. Він пропонує швидкі, гнучкі та
"pandas - це" -> unnecessary 
"пакет" чи "бібліотека"? [Документація з python](https://docs.python.org/uk/3/library/index.html) використовує слово "бібліотека"

2024-07-01 08:35 UTC, YehorBoiar commented on glossary.yml
> +      виразні структури даних, щоб легко та інтуїтивно взаємодіяти зі структурованими даними
I'm not sure how "швидкі, гнучкі та виразні" contribute to the term. Should we write something like: "пропонує структури даних Series і DataFrame. Series можна уявити як одновимірний масив (список) з мітками, а DataFrame — як двовимірну таблицю (подібну до електронної таблиці або бази даних), яка містить рядки і стовпці з мітками." instead?

2024-07-01 08:35 UTC, YehorBoiar commented on glossary.yml
> +      та часовими рядами. Це потужний інструмент для аналізу та маніпулювання даними.
"часовими" -> "числовими"?
I think the last sentence repeats second sentence, we can get rid of that

2024-07-01 23:15 UTC, olexandr-konovalov commented on glossary.yml
> +      та часовими рядами. Це потужний інструмент для аналізу та маніпулювання даними.
Обережно з перекладом терміну time series - перевірте ще

2024-07-03 10:23 UTC, VeronikaShevc commented on glossary.yml
> +      pandas - це пакет Python з відкритим вихідним кодом. Він пропонує швидкі, гнучкі та
Бібліотека підходить більше

2024-07-03 10:25 UTC, VeronikaShevc commented on glossary.yml
> +      виразні структури даних, щоб легко та інтуїтивно взаємодіяти зі структурованими даними
А не буде це занадто довго?

2024-07-03 10:27 UTC, VeronikaShevc commented on glossary.yml
> +      та часовими рядами. Це потужний інструмент для аналізу та маніпулювання даними.
Я думаю, там повинен бути "часовий ряд". Є такий термін.

2024-07-04 09:16 UTC, YehorBoiar requested changes
Looks much better to me! However, I have few suggestions that we can discuss.

2024-07-04 09:16 UTC, YehorBoiar commented on glossary.yml
> +      Бібліотека Python з відкритим вихідним кодом. Вона пропонує структури даних Series і DataFrame.
"Бібліотека Python з відкритим вихідним кодом." -> "Бібліотека з відкритим вихідним кодом для мови Python."
Sounds a little bit better to me. 

"Вона пропонує структури даних Series і DataFrame." -> "Вона надає структури даних Series та DataFrame."
 The verb "надає" (provides) is a little bit better in this context than "пропонує" (offers).

2024-07-04 09:16 UTC, YehorBoiar commented on glossary.yml
> +      Це дозволяє легко та інтуїтивно взаємодіяти зі структурованими даними та часовими рядами.
"Це дозволяє легко" -> "Ця бібліотека дозволяє легко"

2024-07-04 10:36 UTC, YehorBoiar approved these changes
LGTM!

2024-07-04 20:14 UTC, olexandr-konovalov commented on glossary.yml
> +      (подібну до електронної таблиці або бази даних), яка містить рядки і стовпці з мітками.
What does "рядки і стовпці з мітками" mean?

2024-07-04 22:16 UTC, olexandr-konovalov commented on glossary.yml
> +      Бібліотека з відкритим вихідним кодом для мови Python. Вона надає структури даних Series і DataFrame.
Мабуть змінити "надає" на "дозволяє використовувати" ?

2024-07-04 22:18 UTC, olexandr-konovalov commented on glossary.yml
> +      Бібліотека з відкритим вихідним кодом для мови Python. Вона надає структури даних Series і DataFrame.
Також Series і DataFrame -> Series та DataFrame

(англійський текст, розділений "і" складніше зрозуміти)

2024-07-13 21:24 UTC, olexandr-konovalov commented on glossary.yml
> +      Ця бібліотека дозволяє легко та інтуїтивно взаємодіяти зі структурованими даними та часовими рядами.
взаємодіяти чи оперувати ?

2024-07-13 21:26 UTC, olexandr-konovalov commented on glossary.yml
> +      Бібліотека з відкритим вихідним кодом для мови Python. Вона надає структури даних Series і DataFrame.
Мабуть буде краще звучати, якщо сказати

Вона надає такі структури даних, як Series та DataFrame

Що думаєте?

2024-07-14 16:36 UTC, VeronikaShevc commented on glossary.yml
> +      Бібліотека з відкритим вихідним кодом для мови Python. Вона надає структури даних Series і DataFrame.
Так, виправлю на "Вона надає такі структури даних, як Series та DataFrame".

2024-07-14 16:39 UTC, VeronikaShevc commented on glossary.yml
> +      Ця бібліотека дозволяє легко та інтуїтивно взаємодіяти зі структурованими даними та часовими рядами.
"Оперувати " - краще. Зміню на це

2024-07-14 20:50 UTC, olexandr-konovalov approved these changes
LGTM! @YehorBoiar could you please check this too

2024-07-16 09:37 UTC, YehorBoiar requested changes

2024-07-16 09:37 UTC, YehorBoiar commented on glossary.yml
> +      Бібліотека з відкритим вихідним кодом для мови Python. Вона надає такі структури даних, як Series та DataFrame.
What about adding that pandas is created to precess and analyse data

"Бібліотека з відкритим вихідним кодом для мови Python, призначена для обробки та аналізу даних. Вона надає такі структури даних, як Series та DataFrame."?

2024-07-16 09:37 UTC, YehorBoiar commented on glossary.yml
> +      Series можна уявити як одновимірний масив (список) з індексами, а DataFrame — як двовимірну таблицю
"як двовимірну  (подібну до електронної таблиці або бази даних), яка містить рядки і стовпці." -> "двовимірну таблицю, подібну до електронної таблиці або бази даних, яка містить рядки та стовпці."

Використання дужок може створювати враження вставного речення, яке дещо вибивається із загального потоку тексту. Заміна дужок на коми інтегрує пояснення у речення, роблячи його більш плавним і зв'язним.

2024-07-23 20:47 UTC, olexandr-konovalov approved these changes
@YehorBoiar please check new version

2024-07-24 09:25 UTC, YehorBoiar requested changes

2024-07-24 09:25 UTC, YehorBoiar commented on glossary.yml
> +      Series можна уявити як одновимірний масив (список) з індексами, а DataFrame — як двовимірну таблицю,
"Series можна уявити як одновимірний масив (список) з індексами, а DataFrame — як двовимірну таблицю, подібну до електронної таблиці або бази даних, яка містить рядки та стовпці." -> "Series представляє собою одновимірний масив (список) з індексами, а DataFrame — двовимірну таблицю, подібну до електронної таблиці або бази даних, з рядками та стовпцями." 

 This change simplifies the description by removing redundant words and making the sentence more direct. "представляє собою" is a more formal and precise way of describing the concept than "можна уявити як".

2024-07-24 10:39 UTC, olexandr-konovalov commented on glossary.yml
> +      Series можна уявити як одновимірний масив (список) з індексами, а DataFrame — як двовимірну таблицю,
+1

2024-07-28 21:13 UTC, olexandr-konovalov approved these changes
LGTM! Your turn @YehorBoiar

2024-07-29 08:16 UTC, YehorBoiar commented on glossary.yml
> +      Ця бібліотека дозволяє легко та інтуїтивно оперувати структурованими даними та часовими рядами.
"оперувати" -> "працювати"? 

Second option sounds better for me.

2024-07-29 10:10 UTC, olexandr-konovalov commented on glossary.yml
> +      Ця бібліотека дозволяє легко та інтуїтивно оперувати структурованими даними та часовими рядами.
Agree! That is, "працювати із структурованими даними" - @VeronikaShevc please update

2024-07-29 14:37 UTC, merged