Translate "README" to Ukrainian
carpentries/glosario pull request #733
Opened 2024-06-30 20:58 UTC by VeronikaShevc

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Veronika Shevchenko

## Language: 

- Ukrainian

## Terms defined:

- README

2024-06-30 22:52 UTC, olexandr-konovalov requested changes

2024-06-30 22:52 UTC, olexandr-konovalov commented on glossary.yml
> +      Звичайний текстовий файл, що містить важливу інформацію стосовно проєкту або програмного комплексу.
1) мається на увазі, що файл у текстовому форматі, тому "звичайний" - це не дуже точно

Краще "Файл у текстовому форматі, що містить..."

2) "стосовно проєкту або програми" (чому саме "комплексу"?)

2024-07-03 22:40 UTC, olexandr-konovalov approved these changes
LGTM - 2nd review needed

2024-07-04 09:31 UTC, YehorBoiar commented on glossary.yml
> +      Файл у текстовому форматі, що містить важливу інформацію стосовно проєкту або пакета програмного забезпечення.
"що" -> "який"

2024-07-04 10:37 UTC, YehorBoiar approved these changes
LGTM!

2024-07-04 20:08 UTC, merged