Translate "command_line_argument" to Ukrainian
carpentries/glosario pull request #736
Opened 2024-07-14 18:10 UTC by VeronikaShevc

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Veronika Shevchenko

## Language: 

- Ukrainian

## Terms defined:

- command_line_argument

2024-07-16 09:22 UTC, ViktoriiaGrivina approved these changes

2024-07-16 09:49 UTC, YehorBoiar requested changes

2024-07-16 09:49 UTC, YehorBoiar commented on glossary.yml
> +      Назва файла або прапорець, який надається програмі командного рядка під час її запуску.
"Назва файла або прапорець," -> "Назва файлу, прапорець або інша інформація,"

2024-07-16 09:49 UTC, YehorBoiar commented on glossary.yml
> +      Назва файла або прапорець, який надається програмі командного рядка під час її запуску.
Заміна "який" на "яку" для узгодженості з "інформація"

2024-07-16 15:21 UTC, olexandr-konovalov commented on glossary.yml
> +      Назва файла або прапорець, який надається програмі командного рядка під час її запуску.
Мабуть "назва файлу, опція або інша інформація" ? "Опція" відповідає термінології перекладу урока по UNIX Shell

2024-07-16 15:22 UTC, olexandr-konovalov commented on glossary.yml
> +      Назва файла або прапорець, який надається програмі командного рядка під час її запуску.
Так - але за умови змін, запропонованих у попередньому коментарі

2024-07-18 09:13 UTC, YehorBoiar commented on glossary.yml
> +      Назва файла або прапорець, який надається програмі командного рядка під час її запуску.
+1

2024-07-18 10:01 UTC, ViktoriiaGrivina approved these changes

2024-07-18 11:24 UTC, olexandr-konovalov commented on glossary.yml
> +      Назва файлу, опція або інша інформація, яка надається програмі командного рядка під час її запуску.
@VeronikaShevc якщо в англійській "command-line program" є зрозумілим,  "програмі командного рядка" здається не зовсім точним перекладом. Мабуть 

    надається програмі під час її запуску з командного рядка

або 

    надається програмі під час її запуску через інтерфейс командного рядка

2024-07-18 15:38 UTC, YehorBoiar commented on glossary.yml
> +      Назва файлу, опція або інша інформація, яка надається програмі командного рядка під час її запуску.
"яка надається" -> "яку передають"?

2024-07-18 22:10 UTC, olexandr-konovalov commented on glossary.yml
> +      Назва файлу, опція або інша інформація, яка надається програмі командного рядка під час її запуску.
+1 for "яку передають"

2024-07-19 15:39 UTC, olexandr-konovalov approved these changes
LGTM! @YehorBoiar @ViktoriiaGrivina please check hopefully final version one more time

2024-07-20 12:53 UTC, YehorBoiar approved these changes
lgtm!

2024-07-22 12:10 UTC, ViktoriiaGrivina approved these changes

2024-07-22 13:02 UTC, merged