Translate "folder" to Ukrainian
carpentries/glosario pull request #737
Opened 2024-07-14 18:20 UTC by VeronikaShevc

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- Veronika Shevchenko

## Language: 

- Ukrainian

## Terms defined:

- folder

2024-07-16 09:51 UTC, YehorBoiar requested changes

2024-07-16 09:51 UTC, YehorBoiar commented on glossary.yml
> +      Ще один термін для [каталогу](#directory).
"Ще один" -> "Інший"?

2024-07-16 15:24 UTC, olexandr-konovalov commented on glossary.yml
> +      Ще один термін для [каталогу](#directory).
Або навіть

    Те ж саме, що і каталог

або 
    
    Синонім каталогу

?

2024-07-18 09:14 UTC, YehorBoiar commented on glossary.yml
> +      Ще один термін для [каталогу](#directory).
Синонім каталогу :+1:

2024-07-18 09:39 UTC, ViktoriiaGrivina commented on glossary.yml
> +      Ще один термін для [каталогу](#directory).
Так, "синонім каталогу" - найкращий варіант.

2024-07-18 09:53 UTC, ViktoriiaGrivina approved these changes

2024-07-18 10:46 UTC, kashpit0507 approved these changes
Correct!

2024-07-18 11:05 UTC, olexandr-konovalov approved these changes

2024-07-18 11:11 UTC, merged

2025-03-31 08:14 UTC, elletjies commented
@all-contributors please add @VeronikaShevc for translation