Update README.md
carpentries/glosario pull request #745
Opened 2024-08-30 08:00 UTC by elletjies

Updated funding details

2024-09-04 15:50 UTC, froggleston requested changes

2024-09-04 15:50 UTC, froggleston commented on README.md
> +To advance data science knowledge and accessibility for our diverse community, we developed Glosario.
I'm not sure we need this sentence here - it would be more suited to the introduction at the top of the page?

2024-09-04 15:50 UTC, froggleston commented on README.md
> +over 12 months (November 2023 through October 2024) to support an upgrade to Glosario, the open-source,
Similarly I don't think we need the "the open-source multilingual glossary for computing terms" sentence as we're already in the glosario repository.

2024-09-04 15:50 UTC, froggleston commented on README.md
>  SADiLaR is one of the collaborators in the finalisation and expansion of the Glosario
Suggest linking to SADiLaR's website - https://sadilar.org/en/

2024-09-05 06:29 UTC, elletjies commented
@froggleston thanks for the feedback. I have updated the document and made some grammar updates

2024-09-05 14:37 UTC, froggleston approved these changes
LGTM! 👍

2024-09-05 14:37 UTC, merged