Traduccion al castellano de varios términos
carpentries/glosario pull request #756
Opened 2024-11-13 11:58 UTC by yabellini

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- @yabellini 

## Language: 

-  Spanish

## Terms defined:

stratified sampling
stream
standard output
standard input
standard error

2024-11-15 00:51 UTC, nicoguaro commented on glossary.yml
> +      Un canal de communication predefinido para un [proceso](#process), usado típicamente typically para
Acá se nos fue "typically"

2024-11-15 00:51 UTC, nicoguaro commented on glossary.yml
> +      Un flujo sequential de datos, como los [bits](#bit) que llegan a travéz de una conexión de red
sequential >> secuencial
travéz >> través

2024-11-15 00:52 UTC, nicoguaro requested changes
Hay un par de errores en la traducción de dos definiciones.

2025-06-11 15:57 UTC, nicoguaro requested changes
I have added several corrections on the spelling of some words.

2025-06-11 15:57 UTC, nicoguaro commented on glossary.yml
> +    term: "error estandar"
Estándar lleva tilde en la segunda sílaba

2025-06-11 15:57 UTC, nicoguaro commented on glossary.yml
> +    def: >
"estándar" en lugar de "estandar"

2025-06-11 15:57 UTC, nicoguaro commented on glossary.yml
> +    def: >
"estandar" >> "estándar"

2025-06-11 20:50 UTC, yabellini commented on glossary.yml
> +    term: "error estandar"
```suggestion
    term: "error estándar"
```

2025-06-11 20:52 UTC, yabellini commented on glossary.yml
> +      Un canal de communication predefinido para un [proceso](#process), usado típicamente typically para
```suggestion
      Un canal de communication predefinido para un [proceso](#process), usado típicamente para
```

2025-06-11 20:53 UTC, yabellini commented on glossary.yml
> +      Selecionar valores dividiendo la población general en grupos [homogeneos](#homogeneous)
```suggestion
      Selecionar valores dividiendo la población general en grupos [homogéneos](#homogeneous)
```

2025-06-11 20:53 UTC, yabellini commented on glossary.yml
> +      Un flujo sequential de datos, como los [bits](#bit) que llegan a travéz de una conexión de red
```suggestion
      Un flujo secuencial de datos, como los [bits](#bit) que llegan a través de una conexión de red 
```

2025-06-11 21:01 UTC, yabellini commented
Hola @nicoguaro todos los cambios hechos.  Muchas gracias! 

Ahora ya se como poner acentos en mi teclado en Ingles, se supone que deberia cometer menos errores de este tipo. 

Tal vez para una proxima en vez de un comentario, podrias directamente hacer la sugerencia con el cambio de la palabra (cuando hacles click con el + para el comentario apretas el iconico que tiene un mas y un menos, eso te crea un bloque que se llama suggestion y directamente cambia el codigo del PR). Entonces la persona autora del PR solo tiene que aceptar tus sugerencias (también puede rechazar), se ahorra tiempo y de paso queda el PR con tu contribicion en los commits del PR. 

Solo es una idea. 😄

2025-06-11 22:27 UTC, nicoguaro commented
> Hola @nicoguaro todos los cambios hechos. Muchas gracias!
> 
> Ahora ya se como poner acentos en mi teclado en Ingles, se supone que deberia cometer menos errores de este tipo.
> 
> Tal vez para una proxima en vez de un comentario, podrias directamente hacer la sugerencia con el cambio de la palabra (cuando hacles click con el + para el comentario apretas el iconico que tiene un mas y un menos, eso te crea un bloque que se llama suggestion y directamente cambia el codigo del PR). Entonces la persona autora del PR solo tiene que aceptar tus sugerencias (también puede rechazar), se ahorra tiempo y de paso queda el PR con tu contribicion en los commits del PR.
> 
> Solo es una idea. 😄

@yabellini, claro que sí. Lo tendré en cuenta.

2025-10-15 13:29 UTC, SaraVilla approved these changes
all suggestions were great and have been addressed- no further comments! Thanks @yabellini and @nicoguaro

2025-10-24 14:06 UTC, nicoguaro approved these changes

2025-10-24 14:07 UTC, merged