Translate "License" into Ukrainian
carpentries/glosario pull request #757
Opened 2024-11-19 13:30 UTC by olexandr-konovalov

2025-05-04 09:30 UTC, vvkharchenko requested changes

2025-05-04 09:30 UTC, vvkharchenko commented on glossary.yml
> +      Юридичний документ, який описує, як щось може бути використане, та ким.
This could be refined "офіційний дозвіл, який регламентує умови використання об'єкта інтелектуальної власності третіми особами."

2025-05-07 15:37 UTC, vvkharchenko approved these changes

2025-05-07 15:37 UTC, olexandr-konovalov commented on glossary.yml
> +      Юридичний документ, який описує, як щось може бути використане, та ким.
Wonderful - initial word-to-word translation was done as a demo for a prospective contributor, it was waiting for you :)

2025-05-07 15:37 UTC, olexandr-konovalov commented
@elletjies could you please merge this? thanks

2025-05-07 15:40 UTC, merged

2025-05-07 15:41 UTC, elletjies commented
@all-contributors please add @vvkharchenko for review